import type { MapData } from "./types";

export const rexInfernus: MapData = {
  id: "rex-infernus",
  number: 50,
  name: "Rex Infernus",
  visible: true,
  logo: { src: "/maps/rex-infernus_logo.png", width: 280, height: 129 },
  tagline: "Interactive Zombies Map",

  image: "/maps/rex-infernus_map.webp",
  imageSize: { width: 5016, height: 5016 },

  floors: [
    { id: "ground", label: "Ground" },
  ],

  // ── Filters / legend ──────────────────────────────────────────────────────
  // One entry per filter toggle. Two ids carry behaviour and should be reused
  // as-is: `perk` gains the extra "Perk Names" toggle, and `ee` is the switch
  // that reveals Easter-egg routes. `group` sets the filter-panel heading.
  categories: [
    {
      id: "perk",
      label: "Perk Machines",
      color: "#22d3ee",
      kind: "icon",
      glyph: "🥤",
      defaultVisible: true,
      description: "Perk-a-Cola vending machines.",
      group: "Perks",
    },
    {
      id: "utility",
      label: "Pack-a-Punch",
      color: "#f59e0b",
      kind: "icon",
      glyph: "P",
      defaultVisible: true,
      description: "Pack-a-Punch machine.",
      group: "Map Markers",
    },
    {
      id: "box",
      label: "Mystery Box",
      color: "#a855f7",
      kind: "icon",
      glyph: "❓",
      defaultVisible: true,
      description: "Possible Mystery Box spawn locations.",
      group: "Map Markers",
    },
    {
      id: "wallbuy",
      label: "Wall Buys",
      color: "#84cc16",
      kind: "icon",
      glyph: "🔫",
      defaultVisible: false,
      description: "Wall-mounted weapon purchases.",
      group: "Map Markers",
    },
    {
      id: "spawn",
      label: "Spawn / Exfil",
      color: "#ef4444",
      kind: "icon",
      glyph: "🚩",
      defaultVisible: true,
      description: "Player spawn and exfil points.",
      group: "Map Markers",
    },
    {
      id: "ee",
      label: "Easter Egg Steps",
      color: "#ec4899",
      kind: "step",
      defaultVisible: true,
      description: "Numbered main-quest step locations.",
      group: "Quest",
    },
  ],

  // ── Icons / markers ───────────────────────────────────────────────────────
  // Every marker needs a unique `id`, a `categoryId` from the list above, a
  // label, and a position. `icon` swaps the category glyph for an image, and
  // `revealImage` is the screenshot shown when the marker is clicked.
  markers: [
    {
      id: "spawn-point",
      categoryId: "spawn",
      label: "Spawn",
      position: { x: 50, y: 95 },
    },
    {
      id: "util-pack-a-punch",
      categoryId: "utility",
      label: "Pack-a-Punch",
      position: { x: 55.2, y: 56.6 },
      icon: "/images/perks/icons/packapunch.png",
    },
    {
      id: "perk-mule-kick",
      categoryId: "perk",
      floor: "ground",
      label: "Mule Kick",
      position: { x: 32.3, y: 24.4 },
      icon: "/images/perks/icons/mulekick.webp",
    },
    {
      id: "perk-juggernog",
      categoryId: "perk",
      floor: "ground",
      label: "Juggernog",
      position: { x: 19, y: 40.9 },
      icon: "/images/perks/icons/juggernog.webp",
    },
    {
      id: "perk-vulture-aid",
      categoryId: "perk",
      floor: "ground",
      label: "Vulture Aid",
      position: { x: 46.8, y: 43.7 },
      icon: "/images/perks/icons/vultureaid.webp",
    },
    {
      id: "perk-widows-wine",
      categoryId: "perk",
      floor: "ground",
      label: "Widow's Wine",
      position: { x: 57.3, y: 26.6 },
      icon: "/images/perks/icons/widowswine.png",
    },
    {
      id: "perk-death-perception",
      categoryId: "perk",
      floor: "ground",
      label: "Death Perception",
      position: { x: 68, y: 37.3 },
      icon: "/images/perks/icons/deathperception.webp",
    },
    {
      id: "perk-phd-flopper",
      categoryId: "perk",
      floor: "ground",
      label: "PHD Flopper",
      position: { x: 88.9, y: 44.8 },
      icon: "/images/perks/icons/phdflopper.webp",
    },
    {
      id: "perk-elemental-pop",
      categoryId: "perk",
      floor: "ground",
      label: "Elemental Pop",
      position: { x: 87.8, y: 59.8 },
      icon: "/images/perks/icons/elementalpop.webp",
    },
    {
      id: "perk-wisp-tea",
      categoryId: "perk",
      floor: "ground",
      label: "Wisp Tea",
      position: { x: 74.1, y: 66.2 },
      icon: "/images/perks/icons/wisptea.webp",
    },
    {
      id: "perk-stamin-up",
      categoryId: "perk",
      floor: "ground",
      label: "Stamin-Up",
      position: { x: 37.3, y: 72.7 },
      icon: "/images/perks/icons/staminup.webp",
    },
    {
      id: "perk-quick-revive",
      categoryId: "perk",
      floor: "ground",
      label: "Quick Revive",
      position: { x: 57.5, y: 78.8 },
      icon: "/images/perks/icons/quickrevive.webp",
    },
    {
      id: "perk-double-tap",
      categoryId: "perk",
      floor: "ground",
      label: "Double Tap",
      position: { x: 17, y: 70.3 },
      icon: "/images/perks/icons/doubletap.webp",
    },
    {
      // Shares a machine with Der Wunderfizz below — it cycles between the
      // two perks. Offset 0.8% apart on y so both markers stay clickable.
      id: "perk-deadshot-daiquiri",
      categoryId: "perk",
      floor: "ground",
      label: "Deadshot Daiquiri",
      position: { x: 55.3, y: 51.6 },
      icon: "/images/perks/icons/deadshotdaiquiri.webp",
      note: "Cycles with Der Wunderfizz at this same machine.",
    },
    {
      id: "perk-der-wunderfizz",
      categoryId: "perk",
      floor: "ground",
      label: "Der Wunderfizz",
      position: { x: 55.3, y: 53.4 },
      icon: "/images/perks/icons/derwunderfizz.png",
      note: "Cycles with Deadshot Daiquiri at this same machine.",
    },
    {
      id: "box-main",
      categoryId: "box",
      label: "Mystery Box",
      position: { x: 60, y: 60 },
      note: "One of the possible box spawns.",
    },
  ],

  // ── Named regions ─────────────────────────────────────────────────────────
  // `label` renders at `position`; a "\n" in it forces a line break. `outline`
  // is the optional zone border — plot it with the Draw tool in Zone mode and
  // close the polygon by repeating the first point.
  areas: [
    {
      id: "her-house",
      label: "Her\nHouse",
      position: { x: 55.7, y: 78.6 },
      color: "#fcd34d",
      outline: [
          { x: 50.8, y: 79.3 },
          { x: 52.1, y: 79.1 },
          { x: 52.9, y: 83.5 },
          { x: 60, y: 82.2 },
          { x: 59.6, y: 80.2 },
          { x: 60.3, y: 79.4 },
          { x: 60.5, y: 78.2 },
          { x: 60.1, y: 76.6 },
          { x: 59.1, y: 75.4 },
          { x: 57.7, y: 74.7 },
          { x: 57.3, y: 74.7 },
          { x: 57, y: 74.1 },
          { x: 56.1, y: 73.7 },
          { x: 55.3, y: 73.9 },
          { x: 54.4, y: 74.1 },
          { x: 53.6, y: 74.1 },
          { x: 52.7, y: 74.7 },
          { x: 52.1, y: 75.3 },
          { x: 51.4, y: 76.1 },
          { x: 50.9, y: 77.1 },
          { x: 50.6, y: 78 },
          { x: 50.6, y: 78.5 },
          { x: 50.8, y: 79.3 }
      ],
    },
    {
      id: "nexus-forge",
      label: "Nexus        Forge",
      position: { x: 55.4, y: 56.6 },
      color: "#f97316",
      outline: [
        { x: 48.6, y: 53 },
        { x: 48.1, y: 54 },
        { x: 47.8, y: 55 },
        { x: 47.6, y: 56.1 },
        { x: 47.6, y: 57.3 },
        { x: 47.6, y: 58 },
        { x: 47.9, y: 59 },
        { x: 48.4, y: 60.2 },
        { x: 51.5, y: 63.5 },
        { x: 52.8, y: 64 },
        { x: 54.8, y: 64.4 },
        { x: 56.6, y: 64.3 },
        { x: 58, y: 63.9 },
        { x: 59, y: 63.5 },
        { x: 62, y: 60.8 },
        { x: 62.7, y: 59.1 },
        { x: 63.1, y: 57.8 },
        { x: 63.1, y: 56.2 },
        { x: 62.8, y: 54.5 },
        { x: 62.2, y: 53.2 },
        { x: 62.6, y: 52.9 },
        { x: 59.2, y: 49.6 },
        { x: 59.1, y: 49.9 },
        { x: 57.9, y: 49.4 },
        { x: 56.7, y: 49.1 },
        { x: 55.3, y: 49 },
        { x: 54, y: 49.1 },
        { x: 53.1, y: 49.3 },
        { x: 52.1, y: 49.7 },
        { x: 51.8, y: 49.3 },
        { x: 51.2, y: 49.5 },
        { x: 51.3, y: 50 },
        { x: 51.3, y: 50.2 },
        { x: 50.8, y: 50.5 },
        { x: 49, y: 52.5 },
        { x: 48.5, y: 52.2 },
        { x: 48.4, y: 52.7 },
        { x: 48.6, y: 53.1 },
      ],
    },
    {
      id: "veytharion-passage",
      label: "Veytharion\nPassage",
      position: { x: 46.5, y: 44.1 },
      color: "#38bdf8",
      outline: [
  { x: 48.5, y: 52.1 },
  { x: 49, y: 52.4 },
  { x: 50.7, y: 50.5 },
  { x: 50, y: 49.2 },
  { x: 50, y: 48.6 },
  { x: 49.3, y: 48.7 },
  { x: 49.2, y: 49.1 },
  { x: 48.5, y: 49.5 },
  { x: 48.3, y: 49.6 },
  { x: 47.8, y: 49.7 },
  { x: 47.7, y: 49.3 },
  { x: 47.4, y: 49.1 },
  { x: 47, y: 48.7 },
  { x: 47, y: 48.4 },
  { x: 46.9, y: 48.1 },
  { x: 46.6, y: 47.9 },
  { x: 46.5, y: 47.7 },
  { x: 46.6, y: 47.4 },
  { x: 46.8, y: 47.2 },
  { x: 47.3, y: 47.3 },
  { x: 48.1, y: 47.5 },
  { x: 48.5, y: 47.5 },
  { x: 49, y: 47.4 },
  { x: 50.1, y: 47.8 },
  { x: 50.8, y: 46.8 },
  { x: 50.4, y: 46.7 },
  { x: 50.9, y: 45.6 },
  { x: 50.9, y: 45.1 },
  { x: 51.5, y: 44.1 },
  { x: 52, y: 43.9 },
  { x: 52.4, y: 43.5 },
  { x: 52.4, y: 42.9 },
  { x: 52, y: 42 },
  { x: 51.3, y: 41.5 },
  { x: 50.5, y: 41.6 },
  { x: 49.6, y: 41.8 },
  { x: 49.6, y: 41.4 },
  { x: 50.1, y: 41 },
  { x: 50.3, y: 40.7 },
  { x: 50.6, y: 40.2 },
  { x: 50.8, y: 39.8 },
  { x: 50.7, y: 39.4 },
  { x: 50.4, y: 38.7 },
  { x: 50.1, y: 38.4 },
  { x: 49.8, y: 38.2 },
  { x: 49.8, y: 37.9 },
  { x: 49.8, y: 37.5 },
  { x: 49.5, y: 36.9 },
  { x: 49.1, y: 36.3 },
  { x: 48.8, y: 36.2 },
  { x: 48.4, y: 36.3 },
  { x: 48.2, y: 36.5 },
  { x: 48.1, y: 36.8 },
  { x: 48, y: 37.1 },
  { x: 47.9, y: 37.5 },
  { x: 47.3, y: 38 },
  { x: 46.9, y: 38.2 },
  { x: 46.6, y: 38.3 },
  { x: 46.3, y: 38.3 },
  { x: 45.6, y: 38.2 },
  { x: 44.6, y: 37.7 },
  { x: 44.1, y: 37.6 },
  { x: 43.7, y: 37.9 },
  { x: 43.4, y: 38.3 },
  { x: 42.9, y: 38.8 },
  { x: 44.8, y: 40.7 },
  { x: 44.4, y: 41.1 },
  { x: 44.5, y: 41.6 },
  { x: 44.5, y: 41.8 },
  { x: 44.2, y: 42.2 },
  { x: 44.6, y: 42.6 },
  { x: 44.2, y: 43 },
  { x: 43.3, y: 42.2 },
  { x: 43, y: 42.5 },
  { x: 40.8, y: 44.6 },
  { x: 40.2, y: 45.2 },
  { x: 40.7, y: 45.8 },
  { x: 40.6, y: 46 },
  { x: 40.7, y: 46.2 },
  { x: 40.8, y: 46.3 },
  { x: 40.8, y: 46.8 },
  { x: 40.9, y: 47.3 },
  { x: 41.1, y: 47.8 },
  { x: 41.3, y: 48.1 },
  { x: 41.8, y: 48.4 },
  { x: 42.3, y: 48.6 },
  { x: 42.9, y: 48.8 },
  { x: 43.6, y: 48.9 },
  { x: 43.8, y: 48.9 },
  { x: 44.1, y: 48.7 },
  { x: 44.6, y: 48.9 },
  { x: 45, y: 48.9 },
  { x: 45.2, y: 48.9 },
  { x: 45.5, y: 49.2 },
  { x: 45.8, y: 49.6 },
  { x: 46, y: 50.1 },
  { x: 46, y: 50.3 },
  { x: 46.5, y: 50.6 },
  { x: 46.7, y: 50.8 },
  { x: 46.8, y: 51.2 },
  { x: 47.3, y: 51.1 },
  { x: 47.9, y: 51.1 },
  { x: 48.3, y: 50.9 },
  { x: 48.5, y: 51.1 },
  { x: 48.4, y: 51.4 },
  { x: 48.1, y: 51.8 },
  { x: 48.5, y: 52.1 }
],
    },
    {
      id: "veytharion-entrance",
      label: "Veytharion\nEntrance",
      position: { x: 40.5, y: 42.1 },
      color: "#a78bfa",
      outline: [
        { x: 40.8, y: 44.6 },
        { x: 40.5, y: 44.3 },
        { x: 40.9, y: 43.9 },
        { x: 40, y: 43 },
        { x: 39.4, y: 43.7 },
        { x: 38, y: 42.4 },
        { x: 40.8, y: 39.6 },
        { x: 42, y: 40.9 },
        { x: 41.4, y: 41.6 },
        { x: 42.2, y: 42.3 },
        { x: 42.5, y: 42 },
        { x: 43, y: 42.4 },
        { x: 40.8, y: 44.6 },
      ],
    },
    {
      id: "nyxara-passage",
      label: "Nyxara Passage",
      position: { x: 41.2, y: 65.4 },
      color: "#2dd4bf",
      outline: [
        { x: 48.4, y: 60.3 },
        { x: 47.5, y: 60.6 },
        { x: 46.6, y: 58.4 },
        { x: 45.8, y: 58.5 },
        { x: 45.8, y: 59 },
        { x: 45.1, y: 59.7 },
        { x: 44.1, y: 59.7 },
        { x: 43.9, y: 59.6 },
        { x: 43.5, y: 59.6 },
        { x: 43.3, y: 59.3 },
        { x: 42.5, y: 60 },
        { x: 42.5, y: 60.3 },
        { x: 42.4, y: 60.5 },
        { x: 42.4, y: 61 },
        { x: 42.6, y: 61.3 },
        { x: 43.1, y: 61.8 },
        { x: 42.1, y: 63.1 },
        { x: 40.6, y: 63.2 },
        { x: 38.9, y: 61.1 },
        { x: 39.2, y: 60.6 },
        { x: 39.3, y: 60.3 },
        { x: 39.3, y: 59.2 },
        { x: 38.9, y: 58.6 },
        { x: 38.2, y: 58.6 },
        { x: 38, y: 58.6 },
        { x: 37.5, y: 58.6 },
        { x: 36.5, y: 58.7 },
        { x: 36.4, y: 59.1 },
        { x: 36.4, y: 59.7 },
        { x: 36.3, y: 60.8 },
        { x: 36.1, y: 61.1 },
        { x: 36.1, y: 62.3 },
        { x: 36.5, y: 62.8 },
        { x: 36.8, y: 62.8 },
        { x: 36.9, y: 63.2 },
        { x: 36.3, y: 63.3 },
        { x: 36.2, y: 63.5 },
        { x: 35.6, y: 63.5 },
        { x: 35.6, y: 64.2 },
        { x: 35.1, y: 64.8 },
        { x: 33.6, y: 65.9 },
        { x: 33.6, y: 66.4 },
        { x: 33.6, y: 68.2 },
        { x: 33.6, y: 68.7 },
        { x: 35.4, y: 70 },
        { x: 35.4, y: 70.5 },
        { x: 36, y: 70.5 },
        { x: 36, y: 71.4 },
        { x: 36.2, y: 71.6 },
        { x: 36.2, y: 72.4 },
        { x: 37.5, y: 73.8 },
        { x: 39, y: 73.8 },
        { x: 39.8, y: 72.2 },
        { x: 40.1, y: 72.2 },
        { x: 40.3, y: 71.4 },
        { x: 40.3, y: 70.3 },
        { x: 40.9, y: 69.7 },
        { x: 41.2, y: 69.6 },
        { x: 41.7, y: 69.2 },
        { x: 43.5, y: 69.2 },
        { x: 43.6, y: 69.6 },
        { x: 44, y: 70 },
        { x: 44.5, y: 70.1 },
        { x: 45.4, y: 70.1 },
        { x: 45.9, y: 69.1 },
        { x: 46, y: 68.2 },
        { x: 46.1, y: 66.6 },
        { x: 46.3, y: 65.9 },
        { x: 47, y: 65.3 },
        { x: 46.8, y: 64.8 },
        { x: 46.4, y: 64.5 },
        { x: 46.9, y: 63.9 },
        { x: 47.4, y: 63.7 },
        { x: 47.7, y: 63.7 },
        { x: 48, y: 63.8 },
        { x: 48.4, y: 64.1 },
        { x: 48.8, y: 64.3 },
        { x: 49, y: 64.5 },
        { x: 49.2, y: 64.7 },
        { x: 49, y: 64.9 },
        { x: 49.1, y: 65.1 },
        { x: 49.3, y: 65.3 },
        { x: 49.4, y: 65.5 },
        { x: 49.8, y: 65.1 },
        { x: 51.5, y: 63.5 },
        { x: 48.4, y: 60.3 },
      ],
    },
    {
      id: "nyxara-entrance",
      label: "Nyxara\nEntrance",
      position: { x: 30.5, y: 67.2 },
      color: "#4ade80",
      outline: [
        { x: 33.6, y: 66.3 },
        { x: 31.6, y: 66.3 },
        { x: 31.6, y: 63.8 },
        { x: 30.5, y: 63.8 },
        { x: 30.5, y: 62.8 },
        { x: 30.3, y: 62.7 },
        { x: 30.3, y: 62.5 },
        { x: 28.8, y: 62.5 },
        { x: 28.8, y: 62.8 },
        { x: 28.9, y: 71.1 },
        { x: 29.5, y: 72 },
        { x: 30.6, y: 72 },
        { x: 30.6, y: 70.5 },
        { x: 31.6, y: 70.5 },
        { x: 31.6, y: 68.5 },
        { x: 32.4, y: 69.2 },
        { x: 33.5, y: 68.2 },
        { x: 33.6, y: 66.3 },
      ],
    },
    {
      id: "dravakar-passage",
      label: "Dravakar\nPassage",
      position: { x: 62.5, y: 48.1 },
      color: "#e879f9",
      outline: [
        { x: 59.2, y: 49.6 },
        { x: 59.6, y: 49 },
        { x: 59.2, y: 48.7 },
        { x: 59.3, y: 48.5 },
        { x: 59, y: 48.3 },
        { x: 59.1, y: 48.2 },
        { x: 58.5, y: 47.7 },
        { x: 59.2, y: 46.8 },
        { x: 59.5, y: 46.9 },
        { x: 60.7, y: 45.7 },
        { x: 60.7, y: 45 },
        { x: 61.2, y: 44.5 },
        { x: 61.3, y: 44.6 },
        { x: 62.4, y: 43.6 },
        { x: 63.8, y: 45 },
        { x: 66.1, y: 46.8 },
        { x: 66.9, y: 47.7 },
        { x: 64.4, y: 50.3 },
        { x: 64.5, y: 50.7 },
        { x: 64.4, y: 51 },
        { x: 64.3, y: 51.3 },
        { x: 64, y: 51.4 },
        { x: 63.7, y: 51.4 },
        { x: 63.5, y: 51.2 },
        { x: 62.6, y: 52 },
        { x: 62.9, y: 52.4 },
        { x: 62.5, y: 52.8 },
        { x: 59.2, y: 49.6 },
      ],
    },
    {
      id: "caltheris-passage",
      label: "Caltheris\nPassage",
      position: { x: 67, y: 63.7 },
      color: "#facc15",
      outline: [
        { x: 62, y: 60.9 },
        { x: 62.2, y: 61.1 },
        { x: 62.2, y: 61.4 },
        { x: 62.5, y: 61.7 },
        { x: 62.9, y: 61.8 },
        { x: 63, y: 62.3 },
        { x: 63.6, y: 62.3 },
        { x: 63.7, y: 61.3 },
        { x: 64.5, y: 61.3 },
        { x: 64.6, y: 61.3 },
        { x: 66.8, y: 61.2 },
        { x: 67, y: 61.2 },
        { x: 67.3, y: 61.7 },
        { x: 67.4, y: 61.9 },
        { x: 67.6, y: 62 },
        { x: 67.8, y: 61.9 },
        { x: 67.8, y: 61.7 },
        { x: 67.9, y: 61.2 },
        { x: 68, y: 61 },
        { x: 68.1, y: 60.9 },
        { x: 68.3, y: 60.9 },
        { x: 68.4, y: 61.1 },
        { x: 68.5, y: 61.3 },
        { x: 69.8, y: 61.2 },
        { x: 69.9, y: 61 },
        { x: 69.9, y: 60.8 },
        { x: 70.3, y: 60.6 },
        { x: 71.5, y: 59.8 },
        { x: 71.8, y: 64.9 },
        { x: 71.6, y: 65 },
        { x: 71.7, y: 65.3 },
        { x: 72, y: 66 },
        { x: 72.6, y: 66.8 },
        { x: 72.8, y: 67.3 },
        { x: 73, y: 67.7 },
        { x: 72.1, y: 68.2 },
        { x: 71.8, y: 67.7 },
        { x: 71.4, y: 67.3 },
        { x: 71.1, y: 67 },
        { x: 69.5, y: 67.5 },
        { x: 69.2, y: 67.3 },
        { x: 69, y: 67.2 },
        { x: 68.8, y: 66.9 },
        { x: 68.3, y: 66.9 },
        { x: 67.9, y: 66.8 },
        { x: 67.4, y: 66.2 },
        { x: 67.2, y: 66.2 },
        { x: 66.8, y: 66.2 },
        { x: 66.3, y: 65.5 },
        { x: 66.2, y: 65.1 },
        { x: 66.2, y: 64.6 },
        { x: 63.7, y: 64.5 },
        { x: 63, y: 64.2 },
        { x: 62.7, y: 64.2 },
        { x: 62.5, y: 64.4 },
        { x: 61.9, y: 64.9 },
        { x: 61.4, y: 65.1 },
        { x: 60.9, y: 65.1 },
        { x: 60.5, y: 64.8 },
        { x: 60.3, y: 64.5 },
        { x: 60.1, y: 64.5 },
        { x: 59.1, y: 63.5 },
        { x: 62, y: 60.9 },
      ],
    },
    {
      id: "caltheris-entrance",
      label: "Caltheris\nEntrance",
      position: { x: 74, y: 62.8 },
      color: "#fb7185",
      outline: [
        { x: 71.5, y: 59.8 },
        { x: 71.7, y: 59.8 },
        { x: 72.8, y: 57.6 },
        { x: 75.1, y: 58.7 },
        { x: 75.1, y: 58.8 },
        { x: 75.9, y: 59.2 },
        { x: 75.1, y: 60.9 },
        { x: 74.5, y: 60.8 },
        { x: 74.3, y: 61.4 },
        { x: 76.1, y: 61.5 },
        { x: 76.2, y: 61.8 },
        { x: 78.2, y: 61.7 },
        { x: 78.2, y: 63.4 },
        { x: 76.1, y: 63.4 },
        { x: 76.1, y: 63.8 },
        { x: 74.8, y: 63.8 },
        { x: 73.8, y: 63.8 },
        { x: 74.3, y: 64.6 },
        { x: 74.4, y: 65 },
        { x: 75.8, y: 67.3 },
        { x: 74.3, y: 68.4 },
        { x: 73, y: 67.2 },
        { x: 72.9, y: 67.3 },
        { x: 72.2, y: 66.3 },
        { x: 71.9, y: 65.6 },
        { x: 71.7, y: 59.8 },
      ],
    },
    {
      id: "caltheris-main-chamber",
      label: "Caltheris Main\nChamber",
      position: { x: 83.1, y: 61.6 },
      color: "#60a5fa",
      outline: [
        { x: 78.3, y: 61.6 },
        { x: 78.4, y: 66.7 },
        { x: 78.8, y: 66.8 },
        { x: 78.9, y: 68.2 },
        { x: 80.7, y: 68.3 },
        { x: 80.8, y: 69.2 },
        { x: 81.4, y: 69.7 },
        { x: 82.2, y: 69.2 },
        { x: 82.2, y: 68.2 },
        { x: 87, y: 68.2 },
        { x: 87, y: 68.4 },
        { x: 87.1, y: 68.7 },
        { x: 87.6, y: 69.2 },
        { x: 88, y: 69.3 },
        { x: 88.6, y: 68.7 },
        { x: 88.6, y: 67.9 },
        { x: 88.9, y: 67.5 },
        { x: 88.7, y: 67 },
        { x: 88.5, y: 66.6 },
        { x: 88, y: 66.4 },
        { x: 87.9, y: 66.3 },
        { x: 88, y: 59.2 },
        { x: 86.8, y: 57.8 },
        { x: 86.1, y: 56.8 },
        { x: 86.1, y: 56.7 },
        { x: 85.9, y: 56.7 },
        { x: 85.9, y: 54.7 },
        { x: 84.8, y: 54.7 },
        { x: 84.8, y: 53.6 },
        { x: 85.6, y: 53.6 },
        { x: 85.7, y: 52.5 },
        { x: 83.1, y: 52.3 },
        { x: 82.8, y: 52.7 },
        { x: 82.7, y: 53.5 },
        { x: 83.2, y: 53.6 },
        { x: 83.3, y: 54.7 },
        { x: 78.3, y: 54.8 },
        { x: 78.3, y: 56.6 },
        { x: 78.9, y: 56.7 },
        { x: 78.9, y: 58.5 },
        { x: 78.3, y: 58.5 },
        { x: 78.3, y: 61.6 },
      ],
    },
    {
      id: "nyxara-main-chamber",
      label: "Nyxara Main\nChamber",
      position: { x: 22.9, y: 67.1 },
      color: "#a3e635",
      outline: [
        { x: 14.6, y: 64.2 },
        { x: 16.3, y: 64.1 },
        { x: 16.7, y: 63.7 },
        { x: 17.1, y: 63.5 },
        { x: 19.8, y: 63.4 },
        { x: 19.7, y: 62.7 },
        { x: 20.1, y: 62.4 },
        { x: 20.7, y: 62.6 },
        { x: 20.9, y: 63 },
        { x: 21, y: 63.4 },
        { x: 21.3, y: 63.6 },
        { x: 21.8, y: 63.5 },
        { x: 21.9, y: 62.5 },
        { x: 21.3, y: 62.4 },
        { x: 21.2, y: 61.7 },
        { x: 21.5, y: 61.6 },
        { x: 21.9, y: 61.4 },
        { x: 21.9, y: 59.2 },
        { x: 22.1, y: 58.7 },
        { x: 24.5, y: 58.7 },
        { x: 24.6, y: 58.5 },
        { x: 26.4, y: 58.6 },
        { x: 26.6, y: 58.7 },
        { x: 27.7, y: 58.7 },
        { x: 27.7, y: 61.3 },
        { x: 27.4, y: 61.3 },
        { x: 27.4, y: 62.6 },
        { x: 27.4, y: 62.8 },
        { x: 28.7, y: 62.7 },
        { x: 28.8, y: 71.1 },
        { x: 27.4, y: 71.1 },
        { x: 27.4, y: 73.1 },
        { x: 27.7, y: 73.2 },
        { x: 27.7, y: 75.8 },
        { x: 26.5, y: 75.8 },
        { x: 26.4, y: 76 },
        { x: 24.4, y: 76 },
        { x: 24.4, y: 75.8 },
        { x: 22.6, y: 75.8 },
        { x: 22.5, y: 74.6 },
        { x: 22.4, y: 74.4 },
        { x: 22.4, y: 73.7 },
        { x: 22, y: 73.1 },
        { x: 22, y: 72.6 },
        { x: 22.2, y: 72.3 },
        { x: 22.1, y: 71.7 },
        { x: 21.9, y: 71.6 },
        { x: 21.5, y: 71.7 },
        { x: 21.1, y: 71.9 },
        { x: 21.1, y: 72.2 },
        { x: 20.3, y: 72.2 },
        { x: 19.9, y: 71.2 },
        { x: 18.4, y: 71.1 },
        { x: 17.6, y: 70.5 },
        { x: 15.5, y: 70.5 },
        { x: 15.5, y: 68.8 },
        { x: 14.7, y: 68.8 },
        { x: 14.6, y: 64.2 },
      ],
    },
    {
      id: "dravakar-main-chamber",
      label: "Dravakar Main\nChamber",
      position: { x: 72, y: 39.3 },
      color: "#c084fc",
      outline: [
        { x: 63.9, y: 45 },
        { x: 64.3, y: 44.5 },
        { x: 64.7, y: 44.9 },
        { x: 65.1, y: 44.7 },
        { x: 65.2, y: 44.9 },
        { x: 65.5, y: 44.6 },
        { x: 64.5, y: 43.4 },
        { x: 66.7, y: 41.2 },
        { x: 67.1, y: 41.7 },
        { x: 68.1, y: 40.7 },
        { x: 67.7, y: 40.4 },
        { x: 67.5, y: 40.4 },
        { x: 65.1, y: 37.9 },
        { x: 67.9, y: 35.1 },
        { x: 71.9, y: 31 },
        { x: 72.2, y: 30.8 },
        { x: 72.4, y: 30.5 },
        { x: 75.9, y: 34.5 },
        { x: 78.7, y: 37.3 },
        { x: 80.3, y: 39.2 },
        { x: 77.2, y: 42.3 },
        { x: 77.7, y: 42.8 },
        { x: 77.1, y: 43.5 },
        { x: 76.2, y: 44.5 },
        { x: 76, y: 44.5 },
        { x: 75.8, y: 44.7 },
        { x: 75.2, y: 44.2 },
        { x: 73.3, y: 46.1 },
        { x: 70.4, y: 43.3 },
        { x: 69.6, y: 44.1 },
        { x: 69.9, y: 44.5 },
        { x: 67.7, y: 46.7 },
        { x: 66.8, y: 45.9 },
        { x: 66.4, y: 46.3 },
        { x: 66.5, y: 46.5 },
        { x: 66.1, y: 46.8 },
        { x: 63.9, y: 45 },
      ],
    },
    {
      id: "dravakar-sanctuary",
      label: "Dravakar Sanctuary",
      position: { x: 79.3, y: 30.5 },
      color: "#f43f5e",
      outline: [
        { x: 72.4, y: 30.5 },
        { x: 80.3, y: 39.1 },
        { x: 86.7, y: 32.7 },
        { x: 84.6, y: 30.6 },
        { x: 84.7, y: 30.5 },
        { x: 84.7, y: 30.3 },
        { x: 85.1, y: 30 },
        { x: 85.2, y: 30.1 },
        { x: 86, y: 29.2 },
        { x: 82, y: 25.2 },
        { x: 80.7, y: 26.4 },
        { x: 78.3, y: 24.1 },
        { x: 78, y: 24.4 },
        { x: 77.7, y: 24.1 },
        { x: 77.9, y: 23.7 },
        { x: 75.8, y: 21.6 },
        { x: 73.1, y: 24.3 },
        { x: 73.1, y: 25.7 },
        { x: 74.5, y: 27.1 },
        { x: 75.8, y: 25.8 },
        { x: 76.4, y: 26.4 },
        { x: 72.4, y: 30.5 },
      ],
    },
    {
      id: "veytharion-main-chamber",
      label: "Veytharion Main\nChamber",
      position: { x: 35.9, y: 37.6 },
      color: "#818cf8",
      outline: [
        { x: 35.3, y: 32.6 },
        { x: 31.4, y: 36.4 },
        { x: 31.7, y: 36.8 },
        { x: 31.4, y: 37.2 },
        { x: 31.5, y: 37.4 },
        { x: 31.1, y: 37.7 },
        { x: 31.6, y: 38.3 },
        { x: 30.8, y: 39 },
        { x: 31.4, y: 39.7 },
        { x: 32.7, y: 38.6 },
        { x: 33.7, y: 39.5 },
        { x: 34.3, y: 40.5 },
        { x: 35.1, y: 41.3 },
        { x: 35.6, y: 40.8 },
        { x: 37, y: 42.3 },
        { x: 37.9, y: 42.4 },
        { x: 40.7, y: 39.5 },
        { x: 40.6, y: 38.5 },
        { x: 38.4, y: 36.1 },
        { x: 38.6, y: 35.9 },
        { x: 36.5, y: 33.7 },
        { x: 36.9, y: 33 },
        { x: 36.4, y: 32.3 },
        { x: 36.4, y: 32 },
        { x: 35.6, y: 32.1 },
        { x: 35.6, y: 32.8 },
        { x: 35.3, y: 32.6 },
      ],
    },
    {
      id: "veytharion-sanctuary",
      label: "Veytharion\nSanctuary",
      position: { x: 32.8, y: 29.1 },
      color: "#f472b6",
      outline: [
        { x: 33.7, y: 34.1 },
        { x: 32.8, y: 33.1 },
        { x: 33.2, y: 32.7 },
        { x: 33.2, y: 30.3 },
        { x: 32.8, y: 29.9 },
        { x: 33.7, y: 28.9 },
        { x: 34.6, y: 29.8 },
        { x: 35.2, y: 29.4 },
        { x: 36.5, y: 30.8 },
        { x: 36.5, y: 31 },
        { x: 36.9, y: 31.4 },
        { x: 37.5, y: 32 },
        { x: 38, y: 31.5 },
        { x: 37.7, y: 31.2 },
        { x: 39.6, y: 29.3 },
        { x: 38.9, y: 28.5 },
        { x: 39.6, y: 27.8 },
        { x: 38, y: 26.2 },
        { x: 38.5, y: 25.7 },
        { x: 37.9, y: 25.1 },
        { x: 39.1, y: 23.9 },
        { x: 39.9, y: 24.6 },
        { x: 40.5, y: 24 },
        { x: 40.5, y: 23.6 },
        { x: 40.5, y: 23.3 },
        { x: 40.3, y: 23.2 },
        { x: 40.2, y: 22.5 },
        { x: 40.5, y: 22 },
        { x: 40.7, y: 21.6 },
        { x: 40.6, y: 21.3 },
        { x: 40.3, y: 20.7 },
        { x: 40.2, y: 20.6 },
        { x: 39.5, y: 19.8 },
        { x: 37.4, y: 22 },
        { x: 37.7, y: 22.3 },
        { x: 36.4, y: 23.6 },
        { x: 35.7, y: 23 },
        { x: 35.2, y: 23.4 },
        { x: 33.9, y: 22.1 },
        { x: 31.8, y: 24.2 },
        { x: 32.5, y: 24.9 },
        { x: 31.6, y: 25.8 },
        { x: 32.1, y: 26.3 },
        { x: 31.6, y: 26.8 },
        { x: 32.5, y: 27.7 },
        { x: 31.8, y: 28.5 },
        { x: 31.6, y: 28.4 },
        { x: 31.4, y: 28.5 },
        { x: 31.2, y: 28.2 },
        { x: 30.6, y: 28.3 },
        { x: 28.8, y: 28.2 },
        { x: 26.5, y: 30.5 },
        { x: 26.4, y: 32.7 },
        { x: 27, y: 33.3 },
        { x: 26.1, y: 34.2 },
        { x: 25.5, y: 33.7 },
        { x: 23.3, y: 36 },
        { x: 25.4, y: 38.1 },
        { x: 27.6, y: 35.8 },
        { x: 27.5, y: 35.7 },
        { x: 28.5, y: 34.7 },
        { x: 28.8, y: 34.9 },
        { x: 30.9, y: 34.9 },
        { x: 31.6, y: 34.3 },
        { x: 32.5, y: 35.3 },
        { x: 33.7, y: 34.1 },
      ],
    },
    {
      id: "nyxara-sanctuary",
      label: "Nyxara\nSanctuary",
      position: { x: 10, y: 64.8 },
      color: "#fdba74",
      outline: [
        { x: 14.6, y: 64.1 },
        { x: 14.6, y: 63.5 },
        { x: 14.2, y: 63.1 },
        { x: 14.1, y: 62.8 },
        { x: 14, y: 62.9 },
        { x: 13.9, y: 62.3 },
        { x: 13.1, y: 62.2 },
        { x: 12.4, y: 62.8 },
        { x: 11.8, y: 62.6 },
        { x: 11.7, y: 62.3 },
        { x: 10.8, y: 62.3 },
        { x: 10.7, y: 60.8 },
        { x: 11.5, y: 60.8 },
        { x: 11.5, y: 54.8 },
        { x: 10.6, y: 54.7 },
        { x: 10.7, y: 53.2 },
        { x: 9.4, y: 53.2 },
        { x: 9.2, y: 52.8 },
        { x: 8.2, y: 52.7 },
        { x: 8.2, y: 60.8 },
        { x: 9, y: 60.8 },
        { x: 9.1, y: 62.3 },
        { x: 8.8, y: 62.4 },
        { x: 8.8, y: 63.5 },
        { x: 9.2, y: 63.5 },
        { x: 9.7, y: 64.3 },
        { x: 10.6, y: 64.2 },
        { x: 11.1, y: 64.9 },
        { x: 10.5, y: 65.6 },
        { x: 9.8, y: 65.2 },
        { x: 9.3, y: 65.5 },
        { x: 9.5, y: 65.8 },
        { x: 8.9, y: 66.2 },
        { x: 8.2, y: 65.3 },
        { x: 7.6, y: 65.3 },
        { x: 7.6, y: 64.9 },
        { x: 6.7, y: 65.3 },
        { x: 6.7, y: 66.1 },
        { x: 6.2, y: 66.5 },
        { x: 5.5, y: 66.2 },
        { x: 5.4, y: 65.7 },
        { x: 5.1, y: 65.7 },
        { x: 5, y: 66.2 },
        { x: 4.3, y: 66.3 },
        { x: 4.3, y: 66.8 },
        { x: 4.7, y: 67 },
        { x: 4.8, y: 67.5 },
        { x: 4.4, y: 67.6 },
        { x: 4.4, y: 68.2 },
        { x: 4.9, y: 68.3 },
        { x: 4.9, y: 68.7 },
        { x: 5.1, y: 68.8 },
        { x: 6.3, y: 68.9 },
        { x: 6.3, y: 69.9 },
        { x: 5.4, y: 69.9 },
        { x: 5.4, y: 71.2 },
        { x: 6.3, y: 71.2 },
        { x: 6.3, y: 72.3 },
        { x: 9.4, y: 72.3 },
        { x: 9.4, y: 73 },
        { x: 11.1, y: 73 },
        { x: 11.1, y: 71.9 },
        { x: 11.7, y: 71.1 },
        { x: 12.8, y: 71.1 },
        { x: 12.7, y: 69.5 },
        { x: 13.6, y: 68.8 },
        { x: 14.2, y: 69.3 },
        { x: 14.7, y: 68.8 },
        { x: 14.6, y: 64.1 },
      ],
    },
    {
      id: "spira-insula",
      label: "Spira Insula",
      position: { x: 15.9, y: 46.1 },
      color: "#22c55e",
      outline: [
        { x: 8.2, y: 52.7 },
        { x: 9.2, y: 47.2 },
        { x: 11.9, y: 47.3 },
        { x: 12.1, y: 47 },
        { x: 13.1, y: 46.9 },
        { x: 14, y: 46.5 },
        { x: 14.4, y: 46 },
        { x: 14.5, y: 45.3 },
        { x: 14.1, y: 44.3 },
        { x: 13.3, y: 44.3 },
        { x: 13.3, y: 43.8 },
        { x: 14.2, y: 43.1 },
        { x: 15.1, y: 43.1 },
        { x: 16, y: 44 },
        { x: 16.2, y: 43.8 },
        { x: 16.7, y: 43.8 },
        { x: 17.1, y: 43.4 },
        { x: 17.7, y: 42.9 },
        { x: 18, y: 42 },
        { x: 18.5, y: 41.6 },
        { x: 18.8, y: 41.2 },
        { x: 19.2, y: 40.9 },
        { x: 19.5, y: 40.6 },
        { x: 19.5, y: 40.1 },
        { x: 20.9, y: 39.3 },
        { x: 20.8, y: 38.6 },
        { x: 23.3, y: 36.1 },
        { x: 25.4, y: 38.1 },
        { x: 24.6, y: 39.2 },
        { x: 24.6, y: 39.8 },
        { x: 24.3, y: 40.3 },
        { x: 23.9, y: 40.4 },
        { x: 21.7, y: 41.4 },
        { x: 20.8, y: 42 },
        { x: 20.6, y: 42.6 },
        { x: 19.5, y: 43 },
        { x: 19.4, y: 43.6 },
        { x: 19.8, y: 44 },
        { x: 19.4, y: 44.5 },
        { x: 19.2, y: 44.4 },
        { x: 18.9, y: 44.8 },
        { x: 18.6, y: 45 },
        { x: 18.5, y: 45.4 },
        { x: 18.1, y: 45.8 },
        { x: 18.5, y: 46.8 },
        { x: 18.2, y: 47.1 },
        { x: 18.3, y: 47.5 },
        { x: 18.6, y: 47.7 },
        { x: 18.4, y: 48 },
        { x: 18.1, y: 47.9 },
        { x: 17.7, y: 48.2 },
        { x: 17.3, y: 50.1 },
        { x: 16.9, y: 50.1 },
        { x: 16.6, y: 49.7 },
        { x: 15.6, y: 49.6 },
        { x: 15.1, y: 50.3 },
        { x: 15, y: 50.6 },
        { x: 15, y: 50.8 },
        { x: 14.5, y: 51 },
        { x: 14.5, y: 51.2 },
        { x: 14.4, y: 51.5 },
        { x: 14.1, y: 51.8 },
        { x: 13.7, y: 51.9 },
        { x: 13.3, y: 51.8 },
        { x: 13.4, y: 53.1 },
        { x: 10.7, y: 53.2 },
        { x: 9.4, y: 53.2 },
        { x: 9.2, y: 52.8 },
        { x: 8.2, y: 52.7 },
      ],
    },
    {
      id: "aranea-insula",
      label: "Aranea Insula",
      position: { x: 57.3, y: 28.4 },
      color: "#0d9488",
      outline: [
        { x: 40.2, y: 20.5 },
        { x: 44.6, y: 20.6 },
        { x: 45.6, y: 19.5 },
        { x: 46.6, y: 18.9 },
        { x: 47.5, y: 18.8 },
        { x: 48.3, y: 19 },
        { x: 48.8, y: 19.4 },
        { x: 49.5, y: 19.9 },
        { x: 50.1, y: 20.3 },
        { x: 50.9, y: 20.3 },
        { x: 52.6, y: 19.3 },
        { x: 57.1, y: 19.3 },
        { x: 58, y: 20.3 },
        { x: 58.6, y: 20.3 },
        { x: 60.1, y: 19.3 },
        { x: 63.1, y: 19.4 },
        { x: 63.8, y: 20.3 },
        { x: 64.6, y: 20.3 },
        { x: 65.8, y: 20.3 },
        { x: 68.4, y: 22.8 },
        { x: 74.5, y: 22.8 },
        { x: 73.1, y: 24.3 },
        { x: 73.1, y: 25.8 },
        { x: 74.5, y: 27 },
        { x: 75.8, y: 25.9 },
        { x: 76.3, y: 26.5 },
        { x: 65.1, y: 37.9 },
        { x: 50.8, y: 39.7 },
        { x: 50.5, y: 38.7 },
        { x: 49.8, y: 38.2 },
        { x: 49.8, y: 37.4 },
        { x: 49.2, y: 36.3 },
        { x: 48.7, y: 36.1 },
        { x: 40, y: 24.6 },
        { x: 40.5, y: 24.1 },
        { x: 40.6, y: 23.4 },
        { x: 40.4, y: 23.2 },
        { x: 40.2, y: 22.5 },
        { x: 40.9, y: 21.6 },
        { x: 40.3, y: 20.5 },
      ],
    },
    {
      id: "ruinas-insula",
      label: "Ruinas Insula",
      position: { x: 84.2, y: 46.5 },
      color: "#d946ef",
      outline: [
        { x: 75.8, y: 44.7 },
        { x: 83, y: 52.4 },
        { x: 85.8, y: 52.5 },
        { x: 89.2, y: 48.6 },
        { x: 91.9, y: 44 },
        { x: 90.2, y: 43.1 },
        { x: 89.6, y: 43.9 },
        { x: 87.9, y: 42.8 },
        { x: 88.1, y: 42 },
        { x: 87.2, y: 41.4 },
        { x: 86.8, y: 41.6 },
        { x: 86, y: 41.4 },
        { x: 85.3, y: 41.4 },
        { x: 84.6, y: 41.8 },
        { x: 83.9, y: 41.9 },
        { x: 83.7, y: 42 },
        { x: 83.5, y: 41.6 },
        { x: 82.7, y: 41.6 },
        { x: 82.3, y: 42.2 },
        { x: 82.4, y: 42.8 },
        { x: 82.5, y: 43.1 },
        { x: 82.4, y: 43.5 },
        { x: 82.2, y: 44 },
        { x: 82.1, y: 44.2 },
        { x: 81.5, y: 44.6 },
        { x: 81.3, y: 44.8 },
        { x: 81.2, y: 44.9 },
        { x: 78.4, y: 42.1 },
        { x: 75.8, y: 44.7 },
      ],
    },
    {
      id: "nyxara-inner-sanctuary",
      label: "Nyxara Inner Sanctuary",
      position: { x: 16.8, y: 76.9 },
      color: "#fde047",
      outline: [
        { x: 26.5, y: 76 },
        { x: 26.5, y: 78.3 },
        { x: 9.2, y: 78.5 },
        { x: 9.3, y: 73.1 },
        { x: 11.1, y: 73 },
        { x: 11.3, y: 76 },
        { x: 24.4, y: 76 },
        { x: 26.5, y: 76 },
      ],
    },
  ],

  // ── Easter eggs ───────────────────────────────────────────────────────────
  // A quest is stages of steps. Each step draws a dotted `path` on the map with
  // its `icon` at the end; `locations` replaces that with numbered circles when
  // an objective can spawn in one of several spots.
  eggs: [
    {
      // TODO: rename once the full quest / stage breakdown is known — this is
      // a placeholder container for the first real step.
      id: "main-quest",
      name: "Main Quest",
      color: "#ec4899",
      stages: [
        {
          id: "stage-1",
          title: "Open the Map",
          steps: [
            {
              id: "s1-activate-pack-a-punch",
              title: "Activate Pack-a-Punch",
              instruction:
                "- Unlock the House doors and go downstairs to the telephone. When a new round starts, the phone will ring.\n- Answer the phone and go through the portal to the Nexus Forge.\n- Place the World Seed into the centre of the Nexus Forge.\n- Follow and defeat the two Dread skulls.\n- Interact with the Usurped Flame each drops, and carry each flame back to the Forge to ignite its matching brazier.\n- Once both sides are lit, use the crank wheels around the Forge.\n- Pack-a-Punch is now active.",
              icon: "/images/easteregg/flame.svg",
              path: [
                { x: 57.1, y: 78.1 },
                { x: 57.7, y: 81.1 },
                { x: 55.3, y: 82.1 },
                { x: 54.3, y: 79 },
                { x: 55, y: 78.7 },
                { x: 54.7, y: 76 },
              ],
              // The portal teleports the player to Nexus Forge, so the icon
              // sits at the forge spot rather than the end of the walked path.
              iconPosition: { x: 55.4, y: 56.8 },
              // Mandatory waypoints along the route above (not alternates), so
              // solid numbered circles rather than dashed "one of several".
              solidMarkers: true,
              locations: [
                {
                  position: { x: 57.1, y: 78.1 },
                  color: "#22c55e",
                  text: "**Starting location** for this route.",
                },
                {
                  position: { x: 54.3, y: 79 },
                  text: "**Phone:** unlock the house doors and head downstairs. When a new round starts, the phone will ring — answer it.",
                },
                {
                  position: { x: 54.7, y: 76 },
                  text: "**Portal:** step through to teleport to the Nexus Forge.",
                },
              ],
            },
            {
              // Deliberately placed early: the symbol sequence takes four rounds to
              // play out, and the payoff is not needed until stage 3.
              id: "s1-house-symbol-sequence",
              title: "Start the House Symbol Sequence",
              instruction:
                "**Do this as early as you can.** It starts a four-round timer you cannot skip later, and you will not need the result until stage 3.\n\n- Look underneath the roof edge/eaves of Her House.\n- Find the small basketball tucked under it.\n- Shoot it.\n\nOver the next **four rounds**, one new symbol appears on the House each round. **Write down the order they appear in** \u2014 you have to reproduce it exactly later.\n\n**Do not shoot the symbols yet.** They are only entered during an exfil round, in stage 3.",
              // Not plotted yet — needs the basketball spot on Her House roof.
            },
          ],
        },
        {
          id: "stage-2",
          title: "Build the Warden's Blight",
          steps: [
            {
              id: "s2-fragment-of-nyxara",
              title: "Get the Fragment of Nyxara",
              instruction:
                "- Make sure you have PhD Flopper or a semtex grenade\n- Go to Dravakar's Main Chamber\n- Stand inside the chamber looking back toward the entrance, above the entrance is a small detached/narrow ledge\n- Wall Jump (or use the grapple) from there across to the top rafter\n- Look at the wall on the right hand side and destroy the breakable section with PhD Flopper or a semtex.\n- Pick up the revealed Fragment of Nyxara",
              path: [
                { x: 72.1, y: 38.8 },
                { x: 70.6, y: 38.3 },
                { x: 70.1, y: 37.6 },
                { x: 69.1, y: 38.5 },
                { x: 70.2, y: 39.4 },
                { x: 70, y: 40.1 },
                { x: 69.4, y: 40.9 },
              ],
              // Numbered steps to follow along the route above, not an icon
              // destination — no `icon`/`iconPosition` on this one.
              solidMarkers: true,
              locations: [
                { position: { x: 72.1, y: 38.8 } }, // 1 — start
                { position: { x: 70.2, y: 39.4 } }, // 2 — 5th path point
                { position: { x: 69.4, y: 40.9 } }, // 3 — final point (wall)
              ],
            },
            {
              id: "s2-purple-astral-flame",
              title: "Create the Purple Astral Flame",
              instruction:
                "- Obtain a grapple.\n- Find a floating purple orb.\n- Grapple the orb and drag it to the centre of Pack-a-Punch.\n- When it is close enough, the orb starts orbiting.\n- Turn the crank on Pack-a-Punch.\n- The Forge absorbs the orb and its fire turns purple.\n- Pick up a purple flame.\n\n**You will repeat this loop many times later:** purple orb \u2192 drag to Pack-a-Punch \u2192 crank \u2192 collect purple flame.",
              path: [
                { x: 56.7, y: 50.6 },
                { x: 55.9, y: 55.8 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 56.7, y: 50.6 } }, // 1 — grapple orb location
                { position: { x: 55.9, y: 55.8 } }, // 2 — Pack-a-Punch
              ],
            },
            {
              id: "s2-nyxara-crystal-laser",
              title: "Complete Nyxara's Crystal Laser",
              instruction:
                "- Take a purple flame from the brazier and run to the far side of Nyxara's Sanctuary\n- Throw the purple fire at the giant eye across the gap\n- A purple laser beam activates.\n- Use a grapple on each crystal the laser is currently hitting to move its position. Move each crystal to make it hit the next crystal.\n- Eventually the beam will reach a position where a crystal is missing.\n- Grapple up to the empty mounting point and insert the Fragment of Nyxara.\n- Continue rotating the crystals until the beam reaches the final receiver and opens the door to the hidden area.\n\n**Tip:** The beam appears to be timed (or perhaps ends based on the round end), so do not start until everyone is ready and try to keep a zombie alive.",
              icon: "/images/easteregg/star.svg",
              path: [
                { x: 55.4, y: 60.8 },
                { x: 44, y: 64 },
                { x: 35, y: 66.3 },
                { x: 34, y: 67.4 },
                { x: 9.4, y: 67.2 },
              ],
              // Thrown across the gap rather than walked, so the icon sits at
              // the eye instead of the last path point (the throw spot).
              iconPosition: { x: 5.9, y: 67.4 },
              solidMarkers: true,
              locations: [
                { position: { x: 55.4, y: 60.8 } }, // 1 — flame location
              ],
            },
            {
              id: "s2-feed-the-tree",
              title: "Feed the Tree and Enter the Silent Forest",
              instruction:
                "- Enter the newly opened room and fall into the Nyxara Inner Sanctuary\n- Interact with the large corrupted tree/vine\n- It begins draining your health/life essence\n- Survive while the process completes\n- When the seed becomes available, interact with it.\n- You are transported to the Silent Area / Forest\n\n**Note:** If you cannot interact with the seed, you may need to advance a round.",
              icon: "/images/easteregg/skull.svg",
              path: [
                { x: 25.3, y: 75.1 },
                { x: 25.2, y: 77.1 },
                { x: 10.2, y: 77.4 },
                { x: 10.1, y: 75.3 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 25.3, y: 75.1 } }, // 1
              ],
            },
            {
              // The Silent Forest isn't on the map, so this is just a single
              // numbered marker with the full instructions — no path.
              id: "s2-warden-blight-parts",
              title: "Collect All 3 Warden's Blight Parts",
              instruction:
                "Collect all 3 Warden's Blight parts scattered around the Silent Forest.\n\n**Item 1 — Cave:** Go toward the very rear of the forest, find the charred body near the cave entrance and interact with it, then collect the part.\n\n**Item 2 — Rock:** Find another corpse in the central area leaning against a large rock, interact and collect the part.\n\n**Item 3 — Burned Cabin:** Find the body and floorboards, melee the plank and interact with the item, then collect the part.\n\nYou can collect all three during one Forest visit if you're fast enough.\n\n**If you get kicked out before getting them all:**\n- Advance the round\n- Feed/use the tree fruit again\n- Return and collect the missing part",
              solidMarkers: true,
              locations: [{ position: { x: 30.4, y: 84.3 } }],
            },
            {
              // "Central lever" in the source notes reads as the front lever
              // near the blue writing (distinct from the actual submit lever
              // inside the central pillar at point 9) — flagged for the user
              // to confirm.
              id: "s2-four-pillars",
              title: "Solve the Four Pillars",
              instruction:
                "Go to Dravakar's Sanctuary. Four pillars each carry a celestial symbol: **galaxy**, **moon**, **star**, and **runner** (the runner is the comet/asteroid).\n\nFour levers control them \u2014 the numbers match the circles on the map:\n- Marker 4, left stairwell \u2192 rotates the two left pillars\n- Marker 3, right stairwell \u2192 rotates the two right pillars\n- Marker 2, front lever by the blue writing \u2192 rotates the front two pillars\n- Marker 5, centre pillar \u2192 **submits your answer \u2014 do not touch it until the end**\n\nInteract with the blue writing (marker 1) and Dravakar speaks one of four riddles. Note which one you get, then use the matching solution below.\n\n**These counts assume no pillar has been moved yet.** If you have already rotated some, use the end directions instead to work out what is left.\n\n**Riddle 1** \u2014 \"I remember the runner that travels to stars, while moons and galaxies stay true.\"\n- Levers: front \u00d72, right stairwell \u00d73\n- Ends as: runner \u2192 west, moon \u2192 north, galaxy \u2192 south, star \u2192 unchanged\n\n**Riddle 2** \u2014 \"I drift to the runner that travels to the moon, who borrows from galaxies when stars stay true.\"\n- Levers: left stairwell \u00d73, front \u00d72, right stairwell \u00d71\n- Ends as: runner \u2192 north, moon \u2192 south, galaxy \u2192 east, star \u2192 west\n\n**Riddle 3** \u2014 \"I drift to stars that remember moons, who borrow the runner that travels the galaxy.\"\n- Levers: left stairwell \u00d71, front \u00d72, right stairwell \u00d72\n- Ends as: runner \u2192 south, star \u2192 north, moon \u2192 east, galaxy \u2192 west\n\n**Riddle 4** \u2014 \"I remember galaxies that drift to moons, who borrow the runner that travels the stars.\"\n- Levers: left stairwell \u00d72, right stairwell \u00d72\n- An older community write-up gives the same answer as: right, right, left, left, submit.\n\nWhen the pillars are set, use the centre pillar lever (marker 5) to submit. If correct, the pillar lowers and reveals an opening in the roof. If wrong, you may have to wait for the next round to retry.",
              path: [
                { x: 78.4, y: 32.6 },
                { x: 81.3, y: 33.7 },
                { x: 79.6, y: 32 },
                { x: 80.8, y: 31.1 },
                { x: 83.3, y: 31.2 },
                { x: 85.7, y: 33.2 },
                { x: 84, y: 30.5 },
                { x: 79.7, y: 26 },
                { x: 81.1, y: 30.1 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 78.4, y: 32.6 }, text: "Interact with the blue writing to hear Dravakar's riddle — note which one you get." }, // 1 — blue wall
                { position: { x: 81.3, y: 33.7 }, text: "Front lever — rotates the front two pillars." }, // 2 — front lever
                { position: { x: 85.7, y: 33.2 }, text: "Right stairwell lever — rotates the two right pillars." }, // 3 — right lever
                { position: { x: 79.7, y: 26 }, text: "Left stairwell lever — rotates the two left pillars." }, // 4 — left lever
                { position: { x: 81.1, y: 30.1 }, text: "Center lever — submits your answer. Do not use until the end." }, // 5 — central pillar lever
              ],
            },
            {
              id: "s2-forge-warden-blight",
              title: "Forge and Pack-a-Punch Warden's Blight",
              instruction:
                "- Look upward.\n- A previously inaccessible room has opened.\n- Grapple up.\n- Interact with the forge/anvil/build point.\n- The three Forest components create the Warden's Blight.\n- Take the Wonder Weapon.\n- Pack-a-Punch it to unlock its alt charge attack (this is needed for next step)",
              solidMarkers: true,
              locations: [{ position: { x: 82, y: 29.3 } }],
            },
          ],
        },
        {
          id: "stage-3",
          title: "Return to the House",
          steps: [
            {
              id: "s3-return-to-house",
              title: "Return to the House",
              instruction:
                "By now the four House symbols should all have appeared (see \"Start the House Symbol Sequence\" in stage 1). You need the order they originally appeared in, and the Pack-a-Punched Warden's Blight.\n\n- Wait until an exfil round starts \u2014 do not enter the symbols before then.\n- On the exfil round, shoot the four House symbols in their original order.\n- Once entered correctly, go and activate Exfil.\n- The objective changes from a normal Exfil to something like \"Go to Her House.\"\n- Complete the Exfil/HVT portion.\n- Use the resulting portal/transport to return to the House.",
              solidMarkers: true,
              locations: [{ position: { x: 55.3, y: 63.8 } }],
            },
            {
              id: "s3-eye-of-the-forge",
              title: "Get the Eye of the Forge",
              instruction:
                "Back inside Her House:\n- Go upstairs to the second floor.\n- Find the zombie window around the bedroom/bathroom area.\n- Through the window you can see the bathroom/shelf/wall area.\n- Equip the Packed Warden's Blight.\n- Fully charge its alternate attack.\n- Fire the charged blast through that zombie window at the relevant shelf/wall area.\n- The Eye of the Forge is revealed/dropped.\n- Pick it up.",
              solidMarkers: true,
              locations: [{ position: { x: 54.8, y: 80.1 } }],
            },
            {
              // Lives here rather than with the other Shadowsmith steps: the
              // pool it opens is where the Eye of the Forge goes, so it has to
              // be done before the grapple upgrade below.
              id: "s3-veytharion-cube-puzzle",
              title: "Veytharion: Solve the Cube Puzzle",
              instruction:
                "**Do this early.** It can be solved any time from the start, and the next step needs it finished — the pool it opens is where the Eye of the Forge goes.\n\n**Find the four elemental cubes**\n\n- **Fire** — on top of a window in Veytharion Sanctuary, next to Mule Kick. Wall-jump to bring it down.\n- **Hand** — on the edge of Veytharion Sanctuary.\n- **Water** — on top of a column in Veytharion Main Chamber, next to a GobbleGum machine.\n- **Plant/Leaf** — near a window in Veytharion Sanctuary, by the four pillars.\n\n**Sources disagree on which perk helps spot them:** our run used Death Perception; the community guide credits Vulture Aid. Either is worth having.\n\n**Solve the puzzle**\n\nThe floor inscription is the whole rule: **fire cannot touch water or leaf/grass.** The Hand is your safe separator, so this is a river-crossing puzzle — never leave fire alone with water or leaf on either side.\n\n- Take Fire + Hand across.\n- Drop Fire on the far side, keep Hand on the transport.\n- Send Hand back.\n- Take Hand + Water across.\n- Rearrange so Hand still sits between the incompatible cubes.\n- Bring Hand back.\n- Take Leaf across, again using Hand as the separator.\n- Finally bring Fire across, keeping Hand between Fire and Water/Leaf.\n\nWhen all four are across, the wall opens and reveals a hidden area with the blue **Soul/Galaxy Pool** and a Mystery Perk machine.",
              solidMarkers: true,
              locations: [{ position: { x: 37.5, y: 39.4 } }],
            },
            {
              id: "s3-upgrade-grapple",
              title: "Upgrade the Grapple at Veytharion's Pool",
              instruction:
                "**Corrected route — the Eye does not go into a green grapple station.** Earlier guides (ours included) said to place the Eye at a green grapple altar near Pack-a-Punch. That is wrong. The Eye goes into Veytharion's blue pool.\n\n- Answer the phone in Her House to reveal the portal back to the main map.\n- Carry the Eye of the Forge back into the main map.\n- Go into Veytharion's chamber, to the blue Soul/Galaxy Pool opened by the cube puzzle.\n- Interact with the pool while carrying the Eye to place it in.\n- The grapple station inside Veytharion's chamber turns from **green to red**.\n- Take that red grapple.\n\nThe red grapple is the upgraded one. Everything in the next stage — ripping the Forge covers open, moving purple orbs — needs it.\n\n**If the pool will not take the Eye,** the cube puzzle is not finished; that area only opens once all four cubes are across.",
              solidMarkers: true,
              locations: [{ position: { x: 37.5, y: 39.4 } }],
            },
          ],
        },
        {
          id: "stage-4",
          title: "Activate the True Nexus Forge",
          steps: [
            {
              id: "s4-rip-eye-panels",
              title: "Rip the Eye Panels off Pack-a-Punch",
              instruction:
                "Carrying the **red grapple** from Veytharion's pool:\n\n- Go to Pack-a-Punch.\n- Look around the structure above and below it, including the Nexus Core.\n- You will see square eye-symbol panels/tiles.\n- Grapple them to rip them away, exposing the web-covered mechanisms underneath.\n- Do the three hanging/rotating Forge structures in the upper area around Pack-a-Punch — these are the ones whose controls you will use to aim the laser.\n- Also clear the concealed mechanism panels downstairs, around Wunderfizz.\n\n**If the panels will not come off,** you are not holding the red grapple. Go back to Veytharion's pool and take it.",
              path: [
                { x: 57.3, y: 50.5 },
                { x: 57.1, y: 52.7 },
                { x: 52.9, y: 53.6 },
                { x: 51.2, y: 56.6 },
                { x: 51.7, y: 59.5 },
                { x: 54.6, y: 61.1 },
                { x: 58.4, y: 59.8 },
                { x: 59.7, y: 57 },
                { x: 57.2, y: 53.1 },
              ],
            },
            {
              id: "s4-clear-the-webs",
              title: "Clear the Webs",
              instruction:
                "**1. Clear the normal webbing**\n\nUnderneath Pack-a-Punch, in the Nexus Core, the exposed gears are covered in webs. Fully charge the Warden's Blight alternate attack and destroy every web that responds to it.\n\n**2. Clear the final web**\n\nThe last, stubborn web will not break with the Wonder Weapon. Make another purple flame (orb \u2192 drag to Pack-a-Punch \u2192 crank \u2192 collect) and shoot that web with the flame instead. As a rule: if a web refuses the charged Wonder Weapon, use a purple flame on it.\n\n**3. Orb into the Forge, crank, then run underneath**\n\n- Grapple another purple orb into the centre of Pack-a-Punch and get it orbiting the Forge.\n- Turn the Pack-a-Punch Forge crank. **The lower control will not work until you have done this.**\n- Immediately run underneath Pack-a-Punch, toward Wunderfizz.\n- Interact with the lever in front of Wunderfizz \u2014 the one you could not use before.\n- The central Forge structures start rotating.\n\n**Treat this as timed.** The reproduced sequence is orb \u2192 crank \u2192 sprint underneath \u2192 activate. It has been done solo in that order, so two players operating controls at once does not appear to be required.\n\nOnce the lower control succeeds, the three large Forge/ring levers become usable on the top side of the Nexus Forge, against the pillars.",
              solidMarkers: true,
              locations: [{ position: { x: 55.3, y: 58.2 } }],
            },
            {
              id: "s4-aim-forge-laser",
              title: "Activate and Aim the Forge Laser",
              instruction:
                "Three levers now control the massive rotating rings around the Nexus Forge. The goal is to line the stone markers up so that together they form a complete **O** aimed at one Shadowsmith's temple.\n\n- Use the three levers to rotate the Forge layers.\n- Align them toward one of the four Shadowsmith temples.\n- When correctly aligned, the Forge fires a huge blue laser at that temple's Place of Power.\n\n**If a control is still hidden,** look for more eye-symbol covers on the rotating structures and rip them off with the upgraded grapple first. You should end up with three usable alignment levers.\n\n**They are not three independent switches.** Each lever moves its own section at a different rate and nudges the other two, so work the relative positions until the O closes rather than trying to set one ring at a time.\n\nYou will repeat this aiming step once per Shadowsmith temple.",
              solidMarkers: true,
              locations: [{ position: { x: 55.4, y: 60.7 } }],
            },
            {
              // Coordinates are the four temple entrances (Caltheris,
              // Dravakar, Veytharion, Nyxara) — independent, not a route.
              id: "s4-shadowsmith-corruptions",
              title: "The Four Shadowsmith Corruptions",
              instruction:
                "Each of the four temples takes three stages here: **acquire** its corrupted item (different per temple), **cleanse** it, then **break** its shackle. Cleansing an altar does not finish a Shadowsmith \u2014 the shackle still has to go.\n\nAnd the shackle is no longer the end of it: each temple then has a floor face tablet, covered in the next stage.\n\n**Cleansing (same for every temple)**\n\n- Take that Shadowsmith's corrupted item to its temple.\n- Place it at the temple's flame altar/cauldron.\n- Return to the Nexus Forge and aim the blue laser at that exact temple.\n- Make another purple flame and bring it back to the temple.\n- Fire the purple flame into the altar three times.\n- Dialogue and effects confirm it worked, and the altar stays lit with purple energy.\n\n**If the item is sitting there and nothing happens, check in this order:**\n- Is the right corruption item placed at this altar?\n- Is the Forge's blue laser actually aimed at this temple?\n- Are you firing a purple flame, not the Wonder Weapon?\n\n**Breaking the shackle (same for every temple)**\n\n- Once the altar is permanently lit, lead a normal zombie close to it.\n- Purple essence flows into one zombie; look closely and it radiates a specific symbol.\n- Activate the nearby Titan Trap so you can read the symbols on the giant's arm shackles.\n- Find the arm carrying the same symbol as the marked zombie.\n- Position the marked zombie so that arm is what kills it.\n- That shackle breaks. Repeat for all four Shadowsmiths.",
              solidMarkers: true,
              locations: [
                { position: { x: 71.6, y: 63 }, text: "**Caltheris** temple entrance." },
                { position: { x: 64.8, y: 45.8 }, text: "**Dravakar** temple entrance." },
                { position: { x: 39.3, y: 41 }, text: "**Veytharion** temple entrance." },
                { position: { x: 31.6, y: 67.4 }, text: "**Nyxara** temple entrance." },
              ],
            },
            {
              id: "s4-dravakar-corruption",
              title: "Shadowsmith 1: Dravakar",
              instruction:
                "- Equip **Shatter Blast** on a normal weapon.\n- Go back up into the Wonder Weapon forge room above Dravakar Sanctuary.\n- Four shields sit around that room.\n- Lure zombies next to a shield and kill them there, so Shatter Blast detonates against it.\n- Use those explosions to break the shields, working through them one at a time.\n- One of them drops Dravakar's corruption item.\n\nPick it up and place it in the Dravakar altar, then follow the cleansing and shackle steps in **The Four Shadowsmith Corruptions**.",
              solidMarkers: true,
              locations: [{ position: { x: 81.9, y: 29.6 } }],
            },
            {
              id: "s4-nyxara-corruption",
              title: "Shadowsmith 2: Nyxara",
              instruction:
                "- Equip **Shadow Rift** on a weapon.\n- Make sure the blue Forge laser is aimed at the Nyxara temple.\n- Return to Nyxara's hidden tree and use the fruit again to enter the Silent Forest.\n- Head toward the cave entrance.\n- Kill zombies with Shadow Rift near the cave, aiming to trigger the actual Shadow Rift effect rather than just landing kills with it equipped.\n- Keep going until a zombie drops the **Corruption Scroll**.\n\nPick it up and place it in the Nyxara altar, then follow the cleansing and shackle steps in **The Four Shadowsmith Corruptions**.",
              solidMarkers: true,
              locations: [{ position: { x: 23.4, y: 67.4 } }],
            },
            {
              id: "s4-caltheris-corruption",
              title: "Shadowsmith 3: Caltheris",
              instruction:
                "**Solve the four pressure plates**\n\nInside Caltheris' chamber are four pressure plates/stones. For each one:\n\n- Stand on the active plate and stay on it \u2014 do not step off.\n- Four glowing lights appear around the chamber.\n- Shoot all four without leaving the plate.\n- Move to the next plate and repeat.\n\nThat is four plates \u00d7 four targets = **16 shots in total**. Completing them opens the hidden section.\n\n**Then claim the Shimmering Thread**\n\n- Interact with the revealed star/light object in the opened section.\n- Purple orbs/wisps appear.\n- Grapple the orbs and collect what they release.\n- Keep going until you receive the **Shimmering Thread**.\n\n**The drop appears to have some RNG** \u2014 there is no known way to force it, so keep releasing and looting orbs until the Thread appears.",
              solidMarkers: true,
              locations: [{ position: { x: 81.2, y: 55.7 } }],
            },
            {
              // Two separate island spawns, hence dashed "one of these" markers
              // rather than solid ones.
              id: "s4-veytharion-corruption",
              status: "unconfirmed",
              title: "Shadowsmith 4: Veytharion — Corruption Item",
              instruction:
                "**The item is found during rain, on one of two islands.** This replaces every earlier lead we published, including the Napalm Burst one — see \"What does not work\" below.\n\nIt comes from a single recent post rather than several independent confirmations, and its provenance has been questioned (players are asking how anyone would organically discover a rain-gated interaction with a near-invisible object), so it stays flagged. The interaction itself is reported to work.\n\n**1. Wait for rain**\n\nThe map has to be **raining**. There is no confirmed way to force it — advance rounds until the weather cycle turns over.\n\n- Interacting with Veytharion's Galaxy Pool was tested as a rain trigger and did **not** reliably cause it. Do not stand there spamming the pool.\n\n**2. Check the PhD island spawn**\n\n- Go to PhD island (Ruinas Insula).\n- Head to the Mystery Box position.\n- Move behind the box and around the corner.\n- Interact at the spawn position and pick the piece up.\n\nIt is described as a **small blue pen-like object**, so it is very easy to miss.\n\n**3. If it is not there, check the Jug island spawn**\n\n- Go to the outer rocky edge near Jugger-Nog (Spira Insula).\n- Find the pointed rock and jump onto/toward its tip.\n- Hold/spam interact.\n\n**Interact even if you cannot see anything.** The report is explicit that the object may not render visibly; there may be a sound cue instead.\n\n**About the \"blue orb\"**\n\nEarly information claimed a grappleable blue orb appears during rain. The newer source doubts the orb is real. Go by the two item spawns above, not by hunting an orb.\n\n**What does not work**\n\nThese were all hunt theories that were tried and produced nothing:\n\n- Napalm Burst kills, and Napalm on the unlit torches\n- Fireworks on the torches\n- Light Mend at the blue pool, or killing Ravagers there\n- Purple flame on the wall circles",
              locations: [
                {
                  position: { x: 84.2, y: 46.5 },
                  text: "**PhD island** (Ruinas Insula) — behind the Mystery Box, around the corner.",
                },
                {
                  position: { x: 15.9, y: 46.1 },
                  text: "**Jug island** (Spira Insula) — the pointed rock on the outer edge; jump to its tip and interact.",
                },
              ],
            },
          ],
        },
        {
          id: "stage-5",
          title: "The Face Tablets and Secondary Lasers",
          steps: [
            {
              // Marker coords are the temple entrances — the exact floor-slab
              // positions inside each temple are not mapped yet.
              id: "s5-face-tablets-overview",
              status: "partial",
              title: "How the Face Tablets Work",
              instruction:
                "**This whole phase is newly discovered and was missing from earlier guides.** After the corruption/cleanse/shackle work, there are four floor **face tablets** (slabs), one per Shadowsmith. Each opens to reveal a device underneath, and each device feeds into a second laser puzzle.\n\n**The prerequisite that catches everyone**\n\nThe Forge's blue laser must be **aimed at the temple whose tablet you are working on**. Reports are consistent that a tablet will not respond otherwise. Expect to walk back to the Nexus Forge and re-aim between tablets.\n\nIf a tablet still does nothing with the beam correctly aimed, the likely cause is that temple's cleanse is not finished — do the purple-flame altar work first.\n\n**Each tablet has its own, quite strange, activation**\n\n- **Nyxara** — go prone on the slab and hold interact.\n- **Dravakar** — stand and hold interact; possibly requires taking heavy damage first.\n- **Caltheris** — stand on it and aim down sights at a Mystery Box for ~30 seconds.\n- **Veytharion** — stand on it and jump about 30 times.\n\nEach is covered as its own step below. The markers here are the temple entrances; the precise slab positions inside each temple are not mapped yet.",
              solidMarkers: true,
              locations: [
                { position: { x: 31.6, y: 67.4 }, text: "**Nyxara** temple." },
                { position: { x: 64.8, y: 45.8 }, text: "**Dravakar** temple." },
                { position: { x: 71.6, y: 63 }, text: "**Caltheris** temple." },
                { position: { x: 39.3, y: 41 }, text: "**Veytharion** temple." },
              ],
            },
            {
              id: "s5-nyxara-tablet",
              status: "partial",
              title: "Tablet 1: Nyxara — Go Prone",
              instruction:
                "- Aim the Forge's blue laser at **Nyxara**.\n- Find Nyxara's floor face/tablet.\n- **Go prone on it.**\n- Hold the interact button.\n\nThe tablet opens, revealing the device underneath.\n\n**If it does not respond,** the reported cause is that Nyxara's cleanse is not complete — go back and finish the purple-flame altar work first.",
              solidMarkers: true,
              locations: [{ position: { x: 31.6, y: 67.4 } }],
            },
            {
              id: "s5-dravakar-tablet",
              status: "unconfirmed",
              title: "Tablet 2: Dravakar — Interact (Condition Unclear)",
              instruction:
                "**This is the least pinned-down of the four.** Two versions are in circulation and it needs another reproduction.\n\n- Aim the Forge's blue laser at **Dravakar**.\n- Find Dravakar's floor tablet.\n\n**Version A (simple):**\n\n- Stand on the tablet.\n- Hold interact.\n\n**Version B (damage-gated):**\n\n- Take a large amount of damage first — described as roughly **five health bars' worth**.\n- Then go prone on the tablet and interact.\n\nTry A first since it costs nothing. If you get it open, note which one worked and how much damage you had taken.",
              solidMarkers: true,
              locations: [{ position: { x: 64.8, y: 45.8 } }],
            },
            {
              id: "s5-caltheris-tablet",
              status: "partial",
              title: "Tablet 3: Caltheris — ADS a Mystery Box",
              instruction:
                "Oddly specific, but this is what is reported:\n\n- Aim the Forge's blue laser at **Caltheris**.\n- Stand on Caltheris' floor tablet.\n- **Aim down sights at a Mystery Box.**\n- Hold ADS on it for roughly **30 seconds**.\n\nThe tablet then opens and reveals the device beneath it.\n\nYou need a Mystery Box actually visible from the slab, so this may depend on where the box has spawned or been moved to.",
              solidMarkers: true,
              locations: [{ position: { x: 71.6, y: 63 } }],
            },
            {
              id: "s5-veytharion-tablet",
              status: "partial",
              title: "Tablet 4: Veytharion — Jump ~30 Times",
              instruction:
                "- Aim the Forge's blue laser at **Veytharion**.\n- Stand directly on Veytharion's face slab.\n- **Jump repeatedly** — around 30 jumps is the reported requirement.\n\nThe slab opens and reveals a disk/device underneath.\n\nThis is the best-corroborated of the four tablets: multiple comments describe the jump count and the disk it exposes.",
              solidMarkers: true,
              locations: [{ position: { x: 39.3, y: 41 } }],
            },
            {
              id: "s5-tablet-lasers",
              status: "partial",
              title: "Activate and Redirect the Tablet Lasers",
              instruction:
                "Once a tablet is open, the device underneath is what actually matters.\n\n- Equip the **Packed Warden's Blight**.\n- Fully charge its alternate attack.\n- Shoot the exposed disk/device with the charged blast.\n- The disk rises and floats up, connecting with the Forge laser.\n- **Shoot the floating disk itself** to change its orientation and redirect the beam.\n\nThat much is confirmed by multiple reports for Veytharion at least.\n\n**Where each redirected laser is ultimately meant to point is not documented.** Nobody has published the final target or what completing all four does, so treat the aiming portion as unfinished rather than following a guessed destination.\n\nSo the late-game loop now looks like: corruption item → cleanse temple → break Titan shackle → aim Forge at temple → open that temple's face tablet → charged Wonder Weapon on the disk → redirect its laser → *(unknown)*.",
              solidMarkers: true,
              locations: [
                { position: { x: 39.3, y: 41 }, text: "**Veytharion** — the best-documented of the four disks." },
                { position: { x: 31.6, y: 67.4 }, text: "**Nyxara** disk." },
                { position: { x: 64.8, y: 45.8 }, text: "**Dravakar** disk." },
                { position: { x: 71.6, y: 63 }, text: "**Caltheris** disk." },
              ],
            },
          ],
        },
        {
          id: "stage-6",
          title: "The Warden",
          steps: [
            {
              id: "s6-inner-sanctum",
              status: "unconfirmed",
              title: "Enter the Warden's Inner Sanctum",
              instruction:
                "**Still the one real gap in the quest.** The chain is now documented much further than it was \u2014 corruption items, cleanses, Titan shackles, face tablets, and the secondary tablet lasers all have reported methods.\n\nWhat nobody has published is the part after that: **once all four secondary lasers are solved, what exactly opens the Inner Sanctum.** The official subreddit wiki still lists Warden's Blight, Main Quest and the Warden boss fight as TBD.\n\nDo not follow leaked or cheated completion steps unless someone has independently reproduced them.",
            },
            {
              id: "s6-warden-boss",
              status: "unconfirmed",
              title: "Defeat the Warden",
              instruction:
                "**Waiting on a legitimate, reproducible route.**\n\nThe Warden is the final confrontation, and a completion cutscene has appeared online, so the quest is finishable. However:\n\n- At least one early completion is disputed as having used cheats/tools.\n- The final target for each redirected tablet laser is undocumented.\n- The boss trigger after the tablet lasers is undocumented.\n\nThis section will be filled in once the steps are confirmed.",
            },
          ],
        },
      ],
    },
  ],
};
