import type { MapData } from "./types";

export const rexInfernus: MapData = {
  id: "rex-infernus",
  number: 50,
  name: "Rex Infernus",
  visible: true,
  logo: { src: "/maps/rex-infernus_logo.png", width: 280, height: 129 },
  tagline: "Interactive Zombies Map",

  image: "/maps/rex-infernus_map.webp",
  imageSize: { width: 5016, height: 5016 },

  floors: [
    { id: "ground", label: "Ground" },
  ],

  // ── Filters / legend ──────────────────────────────────────────────────────
  // One entry per filter toggle. Two ids carry behaviour and should be reused
  // as-is: `perk` gains the extra "Perk Names" toggle, and `ee` is the switch
  // that reveals Easter-egg routes. `group` sets the filter-panel heading.
  categories: [
    {
      id: "perk",
      label: "Perk Machines",
      color: "#22d3ee",
      kind: "icon",
      glyph: "🥤",
      defaultVisible: true,
      description: "Perk-a-Cola vending machines.",
      group: "Perks",
    },
    {
      id: "utility",
      label: "Pack-a-Punch",
      color: "#f59e0b",
      kind: "icon",
      glyph: "P",
      defaultVisible: true,
      description: "Pack-a-Punch machine.",
      group: "Map Markers",
    },
    {
      id: "box",
      label: "Mystery Box",
      color: "#a855f7",
      kind: "icon",
      glyph: "❓",
      defaultVisible: true,
      description: "Possible Mystery Box spawn locations.",
      group: "Map Markers",
    },
    {
      id: "wallbuy",
      label: "Wall Buys",
      color: "#84cc16",
      kind: "icon",
      glyph: "🔫",
      defaultVisible: false,
      description: "Wall-mounted weapon purchases.",
      group: "Map Markers",
    },
    {
      id: "spawn",
      label: "Spawn / Exfil",
      color: "#ef4444",
      kind: "icon",
      glyph: "🚩",
      defaultVisible: true,
      description: "Player spawn and exfil points.",
      group: "Map Markers",
    },
    {
      id: "ee",
      label: "Easter Egg Steps",
      color: "#ec4899",
      kind: "step",
      defaultVisible: true,
      description: "Numbered main-quest step locations.",
      group: "Quest",
    },
  ],

  // ── Icons / markers ───────────────────────────────────────────────────────
  // Every marker needs a unique `id`, a `categoryId` from the list above, a
  // label, and a position. `icon` swaps the category glyph for an image, and
  // `revealImage` is the screenshot shown when the marker is clicked.
  markers: [
    {
      id: "spawn-point",
      categoryId: "spawn",
      label: "Spawn",
      position: { x: 50, y: 95 },
    },
    {
      id: "util-pack-a-punch",
      categoryId: "utility",
      label: "Pack-a-Punch",
      position: { x: 55.2, y: 56.6 },
      icon: "/images/perks/icons/packapunch.png",
    },
    {
      id: "perk-mule-kick",
      categoryId: "perk",
      floor: "ground",
      label: "Mule Kick",
      position: { x: 32.3, y: 24.4 },
      icon: "/images/perks/icons/mulekick.webp",
    },
    {
      id: "perk-juggernog",
      categoryId: "perk",
      floor: "ground",
      label: "Juggernog",
      position: { x: 19, y: 40.9 },
      icon: "/images/perks/icons/juggernog.webp",
    },
    {
      id: "perk-vulture-aid",
      categoryId: "perk",
      floor: "ground",
      label: "Vulture Aid",
      position: { x: 46.8, y: 43.7 },
      icon: "/images/perks/icons/vultureaid.webp",
    },
    {
      id: "perk-widows-wine",
      categoryId: "perk",
      floor: "ground",
      label: "Widow's Wine",
      position: { x: 57.3, y: 26.6 },
      icon: "/images/perks/icons/widowswine.png",
    },
    {
      id: "perk-death-perception",
      categoryId: "perk",
      floor: "ground",
      label: "Death Perception",
      position: { x: 68, y: 37.3 },
      icon: "/images/perks/icons/deathperception.webp",
    },
    {
      id: "perk-phd-flopper",
      categoryId: "perk",
      floor: "ground",
      label: "PHD Flopper",
      position: { x: 88.9, y: 44.8 },
      icon: "/images/perks/icons/phdflopper.webp",
    },
    {
      id: "perk-elemental-pop",
      categoryId: "perk",
      floor: "ground",
      label: "Elemental Pop",
      position: { x: 87.8, y: 59.8 },
      icon: "/images/perks/icons/elementalpop.webp",
    },
    {
      id: "perk-wisp-tea",
      categoryId: "perk",
      floor: "ground",
      label: "Wisp Tea",
      position: { x: 74.1, y: 66.2 },
      icon: "/images/perks/icons/wisptea.webp",
    },
    {
      id: "perk-stamin-up",
      categoryId: "perk",
      floor: "ground",
      label: "Stamin-Up",
      position: { x: 37.3, y: 72.7 },
      icon: "/images/perks/icons/staminup.webp",
    },
    {
      id: "perk-quick-revive",
      categoryId: "perk",
      floor: "ground",
      label: "Quick Revive",
      position: { x: 57.5, y: 78.8 },
      icon: "/images/perks/icons/quickrevive.webp",
    },
    {
      id: "perk-double-tap",
      categoryId: "perk",
      floor: "ground",
      label: "Double Tap",
      position: { x: 17, y: 70.3 },
      icon: "/images/perks/icons/doubletap.webp",
    },
    {
      // Shares a machine with Der Wunderfizz below — it cycles between the
      // two perks. Offset 0.8% apart on y so both markers stay clickable.
      id: "perk-deadshot-daiquiri",
      categoryId: "perk",
      floor: "ground",
      label: "Deadshot Daiquiri",
      position: { x: 55.3, y: 51.6 },
      icon: "/images/perks/icons/deadshotdaiquiri.webp",
      note: "Cycles with Der Wunderfizz at this same machine.",
    },
    {
      id: "perk-der-wunderfizz",
      categoryId: "perk",
      floor: "ground",
      label: "Der Wunderfizz",
      position: { x: 55.3, y: 53.4 },
      icon: "/images/perks/icons/derwunderfizz.png",
      note: "Cycles with Deadshot Daiquiri at this same machine.",
    },
    {
      id: "box-main",
      categoryId: "box",
      label: "Mystery Box",
      position: { x: 60, y: 60 },
      note: "One of the possible box spawns.",
    },
  ],

  // ── Named regions ─────────────────────────────────────────────────────────
  // `label` renders at `position`; a "\n" in it forces a line break. `outline`
  // is the optional zone border — plot it with the Draw tool in Zone mode and
  // close the polygon by repeating the first point.
  areas: [
    {
      id: "her-house",
      label: "Her\nHouse",
      position: { x: 55.7, y: 78.6 },
      color: "#fcd34d",
      outline: [
          { x: 50.8, y: 79.3 },
          { x: 52.1, y: 79.1 },
          { x: 52.9, y: 83.5 },
          { x: 60, y: 82.2 },
          { x: 59.6, y: 80.2 },
          { x: 60.3, y: 79.4 },
          { x: 60.5, y: 78.2 },
          { x: 60.1, y: 76.6 },
          { x: 59.1, y: 75.4 },
          { x: 57.7, y: 74.7 },
          { x: 57.3, y: 74.7 },
          { x: 57, y: 74.1 },
          { x: 56.1, y: 73.7 },
          { x: 55.3, y: 73.9 },
          { x: 54.4, y: 74.1 },
          { x: 53.6, y: 74.1 },
          { x: 52.7, y: 74.7 },
          { x: 52.1, y: 75.3 },
          { x: 51.4, y: 76.1 },
          { x: 50.9, y: 77.1 },
          { x: 50.6, y: 78 },
          { x: 50.6, y: 78.5 },
          { x: 50.8, y: 79.3 }
      ],
    },
    {
      id: "nexus-forge",
      label: "Nexus        Forge",
      position: { x: 55.4, y: 56.6 },
      color: "#f97316",
      outline: [
        { x: 48.6, y: 53 },
        { x: 48.1, y: 54 },
        { x: 47.8, y: 55 },
        { x: 47.6, y: 56.1 },
        { x: 47.6, y: 57.3 },
        { x: 47.6, y: 58 },
        { x: 47.9, y: 59 },
        { x: 48.4, y: 60.2 },
        { x: 51.5, y: 63.5 },
        { x: 52.8, y: 64 },
        { x: 54.8, y: 64.4 },
        { x: 56.6, y: 64.3 },
        { x: 58, y: 63.9 },
        { x: 59, y: 63.5 },
        { x: 62, y: 60.8 },
        { x: 62.7, y: 59.1 },
        { x: 63.1, y: 57.8 },
        { x: 63.1, y: 56.2 },
        { x: 62.8, y: 54.5 },
        { x: 62.2, y: 53.2 },
        { x: 62.6, y: 52.9 },
        { x: 59.2, y: 49.6 },
        { x: 59.1, y: 49.9 },
        { x: 57.9, y: 49.4 },
        { x: 56.7, y: 49.1 },
        { x: 55.3, y: 49 },
        { x: 54, y: 49.1 },
        { x: 53.1, y: 49.3 },
        { x: 52.1, y: 49.7 },
        { x: 51.8, y: 49.3 },
        { x: 51.2, y: 49.5 },
        { x: 51.3, y: 50 },
        { x: 51.3, y: 50.2 },
        { x: 50.8, y: 50.5 },
        { x: 49, y: 52.5 },
        { x: 48.5, y: 52.2 },
        { x: 48.4, y: 52.7 },
        { x: 48.6, y: 53.1 },
      ],
    },
    {
      id: "veytharion-passage",
      label: "Veytharion\nPassage",
      position: { x: 46.5, y: 44.1 },
      color: "#38bdf8",
      outline: [
  { x: 48.5, y: 52.1 },
  { x: 49, y: 52.4 },
  { x: 50.7, y: 50.5 },
  { x: 50, y: 49.2 },
  { x: 50, y: 48.6 },
  { x: 49.3, y: 48.7 },
  { x: 49.2, y: 49.1 },
  { x: 48.5, y: 49.5 },
  { x: 48.3, y: 49.6 },
  { x: 47.8, y: 49.7 },
  { x: 47.7, y: 49.3 },
  { x: 47.4, y: 49.1 },
  { x: 47, y: 48.7 },
  { x: 47, y: 48.4 },
  { x: 46.9, y: 48.1 },
  { x: 46.6, y: 47.9 },
  { x: 46.5, y: 47.7 },
  { x: 46.6, y: 47.4 },
  { x: 46.8, y: 47.2 },
  { x: 47.3, y: 47.3 },
  { x: 48.1, y: 47.5 },
  { x: 48.5, y: 47.5 },
  { x: 49, y: 47.4 },
  { x: 50.1, y: 47.8 },
  { x: 50.8, y: 46.8 },
  { x: 50.4, y: 46.7 },
  { x: 50.9, y: 45.6 },
  { x: 50.9, y: 45.1 },
  { x: 51.5, y: 44.1 },
  { x: 52, y: 43.9 },
  { x: 52.4, y: 43.5 },
  { x: 52.4, y: 42.9 },
  { x: 52, y: 42 },
  { x: 51.3, y: 41.5 },
  { x: 50.5, y: 41.6 },
  { x: 49.6, y: 41.8 },
  { x: 49.6, y: 41.4 },
  { x: 50.1, y: 41 },
  { x: 50.3, y: 40.7 },
  { x: 50.6, y: 40.2 },
  { x: 50.8, y: 39.8 },
  { x: 50.7, y: 39.4 },
  { x: 50.4, y: 38.7 },
  { x: 50.1, y: 38.4 },
  { x: 49.8, y: 38.2 },
  { x: 49.8, y: 37.9 },
  { x: 49.8, y: 37.5 },
  { x: 49.5, y: 36.9 },
  { x: 49.1, y: 36.3 },
  { x: 48.8, y: 36.2 },
  { x: 48.4, y: 36.3 },
  { x: 48.2, y: 36.5 },
  { x: 48.1, y: 36.8 },
  { x: 48, y: 37.1 },
  { x: 47.9, y: 37.5 },
  { x: 47.3, y: 38 },
  { x: 46.9, y: 38.2 },
  { x: 46.6, y: 38.3 },
  { x: 46.3, y: 38.3 },
  { x: 45.6, y: 38.2 },
  { x: 44.6, y: 37.7 },
  { x: 44.1, y: 37.6 },
  { x: 43.7, y: 37.9 },
  { x: 43.4, y: 38.3 },
  { x: 42.9, y: 38.8 },
  { x: 44.8, y: 40.7 },
  { x: 44.4, y: 41.1 },
  { x: 44.5, y: 41.6 },
  { x: 44.5, y: 41.8 },
  { x: 44.2, y: 42.2 },
  { x: 44.6, y: 42.6 },
  { x: 44.2, y: 43 },
  { x: 43.3, y: 42.2 },
  { x: 43, y: 42.5 },
  { x: 40.8, y: 44.6 },
  { x: 40.2, y: 45.2 },
  { x: 40.7, y: 45.8 },
  { x: 40.6, y: 46 },
  { x: 40.7, y: 46.2 },
  { x: 40.8, y: 46.3 },
  { x: 40.8, y: 46.8 },
  { x: 40.9, y: 47.3 },
  { x: 41.1, y: 47.8 },
  { x: 41.3, y: 48.1 },
  { x: 41.8, y: 48.4 },
  { x: 42.3, y: 48.6 },
  { x: 42.9, y: 48.8 },
  { x: 43.6, y: 48.9 },
  { x: 43.8, y: 48.9 },
  { x: 44.1, y: 48.7 },
  { x: 44.6, y: 48.9 },
  { x: 45, y: 48.9 },
  { x: 45.2, y: 48.9 },
  { x: 45.5, y: 49.2 },
  { x: 45.8, y: 49.6 },
  { x: 46, y: 50.1 },
  { x: 46, y: 50.3 },
  { x: 46.5, y: 50.6 },
  { x: 46.7, y: 50.8 },
  { x: 46.8, y: 51.2 },
  { x: 47.3, y: 51.1 },
  { x: 47.9, y: 51.1 },
  { x: 48.3, y: 50.9 },
  { x: 48.5, y: 51.1 },
  { x: 48.4, y: 51.4 },
  { x: 48.1, y: 51.8 },
  { x: 48.5, y: 52.1 }
],
    },
    {
      id: "veytharion-entrance",
      label: "Veytharion\nEntrance",
      position: { x: 40.5, y: 42.1 },
      color: "#a78bfa",
      outline: [
        { x: 40.8, y: 44.6 },
        { x: 40.5, y: 44.3 },
        { x: 40.9, y: 43.9 },
        { x: 40, y: 43 },
        { x: 39.4, y: 43.7 },
        { x: 38, y: 42.4 },
        { x: 40.8, y: 39.6 },
        { x: 42, y: 40.9 },
        { x: 41.4, y: 41.6 },
        { x: 42.2, y: 42.3 },
        { x: 42.5, y: 42 },
        { x: 43, y: 42.4 },
        { x: 40.8, y: 44.6 },
      ],
    },
    {
      id: "nyxara-passage",
      label: "Nyxara Passage",
      position: { x: 41.2, y: 65.4 },
      color: "#2dd4bf",
      outline: [
        { x: 48.4, y: 60.3 },
        { x: 47.5, y: 60.6 },
        { x: 46.6, y: 58.4 },
        { x: 45.8, y: 58.5 },
        { x: 45.8, y: 59 },
        { x: 45.1, y: 59.7 },
        { x: 44.1, y: 59.7 },
        { x: 43.9, y: 59.6 },
        { x: 43.5, y: 59.6 },
        { x: 43.3, y: 59.3 },
        { x: 42.5, y: 60 },
        { x: 42.5, y: 60.3 },
        { x: 42.4, y: 60.5 },
        { x: 42.4, y: 61 },
        { x: 42.6, y: 61.3 },
        { x: 43.1, y: 61.8 },
        { x: 42.1, y: 63.1 },
        { x: 40.6, y: 63.2 },
        { x: 38.9, y: 61.1 },
        { x: 39.2, y: 60.6 },
        { x: 39.3, y: 60.3 },
        { x: 39.3, y: 59.2 },
        { x: 38.9, y: 58.6 },
        { x: 38.2, y: 58.6 },
        { x: 38, y: 58.6 },
        { x: 37.5, y: 58.6 },
        { x: 36.5, y: 58.7 },
        { x: 36.4, y: 59.1 },
        { x: 36.4, y: 59.7 },
        { x: 36.3, y: 60.8 },
        { x: 36.1, y: 61.1 },
        { x: 36.1, y: 62.3 },
        { x: 36.5, y: 62.8 },
        { x: 36.8, y: 62.8 },
        { x: 36.9, y: 63.2 },
        { x: 36.3, y: 63.3 },
        { x: 36.2, y: 63.5 },
        { x: 35.6, y: 63.5 },
        { x: 35.6, y: 64.2 },
        { x: 35.1, y: 64.8 },
        { x: 33.6, y: 65.9 },
        { x: 33.6, y: 66.4 },
        { x: 33.6, y: 68.2 },
        { x: 33.6, y: 68.7 },
        { x: 35.4, y: 70 },
        { x: 35.4, y: 70.5 },
        { x: 36, y: 70.5 },
        { x: 36, y: 71.4 },
        { x: 36.2, y: 71.6 },
        { x: 36.2, y: 72.4 },
        { x: 37.5, y: 73.8 },
        { x: 39, y: 73.8 },
        { x: 39.8, y: 72.2 },
        { x: 40.1, y: 72.2 },
        { x: 40.3, y: 71.4 },
        { x: 40.3, y: 70.3 },
        { x: 40.9, y: 69.7 },
        { x: 41.2, y: 69.6 },
        { x: 41.7, y: 69.2 },
        { x: 43.5, y: 69.2 },
        { x: 43.6, y: 69.6 },
        { x: 44, y: 70 },
        { x: 44.5, y: 70.1 },
        { x: 45.4, y: 70.1 },
        { x: 45.9, y: 69.1 },
        { x: 46, y: 68.2 },
        { x: 46.1, y: 66.6 },
        { x: 46.3, y: 65.9 },
        { x: 47, y: 65.3 },
        { x: 46.8, y: 64.8 },
        { x: 46.4, y: 64.5 },
        { x: 46.9, y: 63.9 },
        { x: 47.4, y: 63.7 },
        { x: 47.7, y: 63.7 },
        { x: 48, y: 63.8 },
        { x: 48.4, y: 64.1 },
        { x: 48.8, y: 64.3 },
        { x: 49, y: 64.5 },
        { x: 49.2, y: 64.7 },
        { x: 49, y: 64.9 },
        { x: 49.1, y: 65.1 },
        { x: 49.3, y: 65.3 },
        { x: 49.4, y: 65.5 },
        { x: 49.8, y: 65.1 },
        { x: 51.5, y: 63.5 },
        { x: 48.4, y: 60.3 },
      ],
    },
    {
      id: "nyxara-entrance",
      label: "Nyxara\nEntrance",
      position: { x: 30.5, y: 67.2 },
      color: "#4ade80",
      outline: [
        { x: 33.6, y: 66.3 },
        { x: 31.6, y: 66.3 },
        { x: 31.6, y: 63.8 },
        { x: 30.5, y: 63.8 },
        { x: 30.5, y: 62.8 },
        { x: 30.3, y: 62.7 },
        { x: 30.3, y: 62.5 },
        { x: 28.8, y: 62.5 },
        { x: 28.8, y: 62.8 },
        { x: 28.9, y: 71.1 },
        { x: 29.5, y: 72 },
        { x: 30.6, y: 72 },
        { x: 30.6, y: 70.5 },
        { x: 31.6, y: 70.5 },
        { x: 31.6, y: 68.5 },
        { x: 32.4, y: 69.2 },
        { x: 33.5, y: 68.2 },
        { x: 33.6, y: 66.3 },
      ],
    },
    {
      id: "dravakar-passage",
      label: "Dravakar\nPassage",
      position: { x: 62.5, y: 48.1 },
      color: "#e879f9",
      outline: [
        { x: 59.2, y: 49.6 },
        { x: 59.6, y: 49 },
        { x: 59.2, y: 48.7 },
        { x: 59.3, y: 48.5 },
        { x: 59, y: 48.3 },
        { x: 59.1, y: 48.2 },
        { x: 58.5, y: 47.7 },
        { x: 59.2, y: 46.8 },
        { x: 59.5, y: 46.9 },
        { x: 60.7, y: 45.7 },
        { x: 60.7, y: 45 },
        { x: 61.2, y: 44.5 },
        { x: 61.3, y: 44.6 },
        { x: 62.4, y: 43.6 },
        { x: 63.8, y: 45 },
        { x: 66.1, y: 46.8 },
        { x: 66.9, y: 47.7 },
        { x: 64.4, y: 50.3 },
        { x: 64.5, y: 50.7 },
        { x: 64.4, y: 51 },
        { x: 64.3, y: 51.3 },
        { x: 64, y: 51.4 },
        { x: 63.7, y: 51.4 },
        { x: 63.5, y: 51.2 },
        { x: 62.6, y: 52 },
        { x: 62.9, y: 52.4 },
        { x: 62.5, y: 52.8 },
        { x: 59.2, y: 49.6 },
      ],
    },
    {
      id: "caltheris-passage",
      label: "Caltheris\nPassage",
      position: { x: 67, y: 63.7 },
      color: "#facc15",
      outline: [
        { x: 62, y: 60.9 },
        { x: 62.2, y: 61.1 },
        { x: 62.2, y: 61.4 },
        { x: 62.5, y: 61.7 },
        { x: 62.9, y: 61.8 },
        { x: 63, y: 62.3 },
        { x: 63.6, y: 62.3 },
        { x: 63.7, y: 61.3 },
        { x: 64.5, y: 61.3 },
        { x: 64.6, y: 61.3 },
        { x: 66.8, y: 61.2 },
        { x: 67, y: 61.2 },
        { x: 67.3, y: 61.7 },
        { x: 67.4, y: 61.9 },
        { x: 67.6, y: 62 },
        { x: 67.8, y: 61.9 },
        { x: 67.8, y: 61.7 },
        { x: 67.9, y: 61.2 },
        { x: 68, y: 61 },
        { x: 68.1, y: 60.9 },
        { x: 68.3, y: 60.9 },
        { x: 68.4, y: 61.1 },
        { x: 68.5, y: 61.3 },
        { x: 69.8, y: 61.2 },
        { x: 69.9, y: 61 },
        { x: 69.9, y: 60.8 },
        { x: 70.3, y: 60.6 },
        { x: 71.5, y: 59.8 },
        { x: 71.8, y: 64.9 },
        { x: 71.6, y: 65 },
        { x: 71.7, y: 65.3 },
        { x: 72, y: 66 },
        { x: 72.6, y: 66.8 },
        { x: 72.8, y: 67.3 },
        { x: 73, y: 67.7 },
        { x: 72.1, y: 68.2 },
        { x: 71.8, y: 67.7 },
        { x: 71.4, y: 67.3 },
        { x: 71.1, y: 67 },
        { x: 69.5, y: 67.5 },
        { x: 69.2, y: 67.3 },
        { x: 69, y: 67.2 },
        { x: 68.8, y: 66.9 },
        { x: 68.3, y: 66.9 },
        { x: 67.9, y: 66.8 },
        { x: 67.4, y: 66.2 },
        { x: 67.2, y: 66.2 },
        { x: 66.8, y: 66.2 },
        { x: 66.3, y: 65.5 },
        { x: 66.2, y: 65.1 },
        { x: 66.2, y: 64.6 },
        { x: 63.7, y: 64.5 },
        { x: 63, y: 64.2 },
        { x: 62.7, y: 64.2 },
        { x: 62.5, y: 64.4 },
        { x: 61.9, y: 64.9 },
        { x: 61.4, y: 65.1 },
        { x: 60.9, y: 65.1 },
        { x: 60.5, y: 64.8 },
        { x: 60.3, y: 64.5 },
        { x: 60.1, y: 64.5 },
        { x: 59.1, y: 63.5 },
        { x: 62, y: 60.9 },
      ],
    },
    {
      id: "caltheris-entrance",
      label: "Caltheris\nEntrance",
      position: { x: 74, y: 62.8 },
      color: "#fb7185",
      outline: [
        { x: 71.5, y: 59.8 },
        { x: 71.7, y: 59.8 },
        { x: 72.8, y: 57.6 },
        { x: 75.1, y: 58.7 },
        { x: 75.1, y: 58.8 },
        { x: 75.9, y: 59.2 },
        { x: 75.1, y: 60.9 },
        { x: 74.5, y: 60.8 },
        { x: 74.3, y: 61.4 },
        { x: 76.1, y: 61.5 },
        { x: 76.2, y: 61.8 },
        { x: 78.2, y: 61.7 },
        { x: 78.2, y: 63.4 },
        { x: 76.1, y: 63.4 },
        { x: 76.1, y: 63.8 },
        { x: 74.8, y: 63.8 },
        { x: 73.8, y: 63.8 },
        { x: 74.3, y: 64.6 },
        { x: 74.4, y: 65 },
        { x: 75.8, y: 67.3 },
        { x: 74.3, y: 68.4 },
        { x: 73, y: 67.2 },
        { x: 72.9, y: 67.3 },
        { x: 72.2, y: 66.3 },
        { x: 71.9, y: 65.6 },
        { x: 71.7, y: 59.8 },
      ],
    },
    {
      id: "caltheris-main-chamber",
      label: "Caltheris Main\nChamber",
      position: { x: 83.1, y: 61.6 },
      color: "#60a5fa",
      outline: [
        { x: 78.3, y: 61.6 },
        { x: 78.4, y: 66.7 },
        { x: 78.8, y: 66.8 },
        { x: 78.9, y: 68.2 },
        { x: 80.7, y: 68.3 },
        { x: 80.8, y: 69.2 },
        { x: 81.4, y: 69.7 },
        { x: 82.2, y: 69.2 },
        { x: 82.2, y: 68.2 },
        { x: 87, y: 68.2 },
        { x: 87, y: 68.4 },
        { x: 87.1, y: 68.7 },
        { x: 87.6, y: 69.2 },
        { x: 88, y: 69.3 },
        { x: 88.6, y: 68.7 },
        { x: 88.6, y: 67.9 },
        { x: 88.9, y: 67.5 },
        { x: 88.7, y: 67 },
        { x: 88.5, y: 66.6 },
        { x: 88, y: 66.4 },
        { x: 87.9, y: 66.3 },
        { x: 88, y: 59.2 },
        { x: 86.8, y: 57.8 },
        { x: 86.1, y: 56.8 },
        { x: 86.1, y: 56.7 },
        { x: 85.9, y: 56.7 },
        { x: 85.9, y: 54.7 },
        { x: 84.8, y: 54.7 },
        { x: 84.8, y: 53.6 },
        { x: 85.6, y: 53.6 },
        { x: 85.7, y: 52.5 },
        { x: 83.1, y: 52.3 },
        { x: 82.8, y: 52.7 },
        { x: 82.7, y: 53.5 },
        { x: 83.2, y: 53.6 },
        { x: 83.3, y: 54.7 },
        { x: 78.3, y: 54.8 },
        { x: 78.3, y: 56.6 },
        { x: 78.9, y: 56.7 },
        { x: 78.9, y: 58.5 },
        { x: 78.3, y: 58.5 },
        { x: 78.3, y: 61.6 },
      ],
    },
    {
      id: "nyxara-main-chamber",
      label: "Nyxara Main\nChamber",
      position: { x: 22.9, y: 67.1 },
      color: "#a3e635",
      outline: [
        { x: 14.6, y: 64.2 },
        { x: 16.3, y: 64.1 },
        { x: 16.7, y: 63.7 },
        { x: 17.1, y: 63.5 },
        { x: 19.8, y: 63.4 },
        { x: 19.7, y: 62.7 },
        { x: 20.1, y: 62.4 },
        { x: 20.7, y: 62.6 },
        { x: 20.9, y: 63 },
        { x: 21, y: 63.4 },
        { x: 21.3, y: 63.6 },
        { x: 21.8, y: 63.5 },
        { x: 21.9, y: 62.5 },
        { x: 21.3, y: 62.4 },
        { x: 21.2, y: 61.7 },
        { x: 21.5, y: 61.6 },
        { x: 21.9, y: 61.4 },
        { x: 21.9, y: 59.2 },
        { x: 22.1, y: 58.7 },
        { x: 24.5, y: 58.7 },
        { x: 24.6, y: 58.5 },
        { x: 26.4, y: 58.6 },
        { x: 26.6, y: 58.7 },
        { x: 27.7, y: 58.7 },
        { x: 27.7, y: 61.3 },
        { x: 27.4, y: 61.3 },
        { x: 27.4, y: 62.6 },
        { x: 27.4, y: 62.8 },
        { x: 28.7, y: 62.7 },
        { x: 28.8, y: 71.1 },
        { x: 27.4, y: 71.1 },
        { x: 27.4, y: 73.1 },
        { x: 27.7, y: 73.2 },
        { x: 27.7, y: 75.8 },
        { x: 26.5, y: 75.8 },
        { x: 26.4, y: 76 },
        { x: 24.4, y: 76 },
        { x: 24.4, y: 75.8 },
        { x: 22.6, y: 75.8 },
        { x: 22.5, y: 74.6 },
        { x: 22.4, y: 74.4 },
        { x: 22.4, y: 73.7 },
        { x: 22, y: 73.1 },
        { x: 22, y: 72.6 },
        { x: 22.2, y: 72.3 },
        { x: 22.1, y: 71.7 },
        { x: 21.9, y: 71.6 },
        { x: 21.5, y: 71.7 },
        { x: 21.1, y: 71.9 },
        { x: 21.1, y: 72.2 },
        { x: 20.3, y: 72.2 },
        { x: 19.9, y: 71.2 },
        { x: 18.4, y: 71.1 },
        { x: 17.6, y: 70.5 },
        { x: 15.5, y: 70.5 },
        { x: 15.5, y: 68.8 },
        { x: 14.7, y: 68.8 },
        { x: 14.6, y: 64.2 },
      ],
    },
    {
      id: "dravakar-main-chamber",
      label: "Dravakar Main\nChamber",
      position: { x: 72, y: 39.3 },
      color: "#c084fc",
      outline: [
        { x: 63.9, y: 45 },
        { x: 64.3, y: 44.5 },
        { x: 64.7, y: 44.9 },
        { x: 65.1, y: 44.7 },
        { x: 65.2, y: 44.9 },
        { x: 65.5, y: 44.6 },
        { x: 64.5, y: 43.4 },
        { x: 66.7, y: 41.2 },
        { x: 67.1, y: 41.7 },
        { x: 68.1, y: 40.7 },
        { x: 67.7, y: 40.4 },
        { x: 67.5, y: 40.4 },
        { x: 65.1, y: 37.9 },
        { x: 67.9, y: 35.1 },
        { x: 71.9, y: 31 },
        { x: 72.2, y: 30.8 },
        { x: 72.4, y: 30.5 },
        { x: 75.9, y: 34.5 },
        { x: 78.7, y: 37.3 },
        { x: 80.3, y: 39.2 },
        { x: 77.2, y: 42.3 },
        { x: 77.7, y: 42.8 },
        { x: 77.1, y: 43.5 },
        { x: 76.2, y: 44.5 },
        { x: 76, y: 44.5 },
        { x: 75.8, y: 44.7 },
        { x: 75.2, y: 44.2 },
        { x: 73.3, y: 46.1 },
        { x: 70.4, y: 43.3 },
        { x: 69.6, y: 44.1 },
        { x: 69.9, y: 44.5 },
        { x: 67.7, y: 46.7 },
        { x: 66.8, y: 45.9 },
        { x: 66.4, y: 46.3 },
        { x: 66.5, y: 46.5 },
        { x: 66.1, y: 46.8 },
        { x: 63.9, y: 45 },
      ],
    },
    {
      id: "dravakar-sanctuary",
      label: "Dravakar Sanctuary",
      position: { x: 79.3, y: 30.5 },
      color: "#f43f5e",
      outline: [
        { x: 72.4, y: 30.5 },
        { x: 80.3, y: 39.1 },
        { x: 86.7, y: 32.7 },
        { x: 84.6, y: 30.6 },
        { x: 84.7, y: 30.5 },
        { x: 84.7, y: 30.3 },
        { x: 85.1, y: 30 },
        { x: 85.2, y: 30.1 },
        { x: 86, y: 29.2 },
        { x: 82, y: 25.2 },
        { x: 80.7, y: 26.4 },
        { x: 78.3, y: 24.1 },
        { x: 78, y: 24.4 },
        { x: 77.7, y: 24.1 },
        { x: 77.9, y: 23.7 },
        { x: 75.8, y: 21.6 },
        { x: 73.1, y: 24.3 },
        { x: 73.1, y: 25.7 },
        { x: 74.5, y: 27.1 },
        { x: 75.8, y: 25.8 },
        { x: 76.4, y: 26.4 },
        { x: 72.4, y: 30.5 },
      ],
    },
    {
      id: "veytharion-main-chamber",
      label: "Veytharion Main\nChamber",
      position: { x: 35.9, y: 37.6 },
      color: "#818cf8",
      outline: [
        { x: 35.3, y: 32.6 },
        { x: 31.4, y: 36.4 },
        { x: 31.7, y: 36.8 },
        { x: 31.4, y: 37.2 },
        { x: 31.5, y: 37.4 },
        { x: 31.1, y: 37.7 },
        { x: 31.6, y: 38.3 },
        { x: 30.8, y: 39 },
        { x: 31.4, y: 39.7 },
        { x: 32.7, y: 38.6 },
        { x: 33.7, y: 39.5 },
        { x: 34.3, y: 40.5 },
        { x: 35.1, y: 41.3 },
        { x: 35.6, y: 40.8 },
        { x: 37, y: 42.3 },
        { x: 37.9, y: 42.4 },
        { x: 40.7, y: 39.5 },
        { x: 40.6, y: 38.5 },
        { x: 38.4, y: 36.1 },
        { x: 38.6, y: 35.9 },
        { x: 36.5, y: 33.7 },
        { x: 36.9, y: 33 },
        { x: 36.4, y: 32.3 },
        { x: 36.4, y: 32 },
        { x: 35.6, y: 32.1 },
        { x: 35.6, y: 32.8 },
        { x: 35.3, y: 32.6 },
      ],
    },
    {
      id: "veytharion-sanctuary",
      label: "Veytharion\nSanctuary",
      position: { x: 32.8, y: 29.1 },
      color: "#f472b6",
      outline: [
        { x: 33.7, y: 34.1 },
        { x: 32.8, y: 33.1 },
        { x: 33.2, y: 32.7 },
        { x: 33.2, y: 30.3 },
        { x: 32.8, y: 29.9 },
        { x: 33.7, y: 28.9 },
        { x: 34.6, y: 29.8 },
        { x: 35.2, y: 29.4 },
        { x: 36.5, y: 30.8 },
        { x: 36.5, y: 31 },
        { x: 36.9, y: 31.4 },
        { x: 37.5, y: 32 },
        { x: 38, y: 31.5 },
        { x: 37.7, y: 31.2 },
        { x: 39.6, y: 29.3 },
        { x: 38.9, y: 28.5 },
        { x: 39.6, y: 27.8 },
        { x: 38, y: 26.2 },
        { x: 38.5, y: 25.7 },
        { x: 37.9, y: 25.1 },
        { x: 39.1, y: 23.9 },
        { x: 39.9, y: 24.6 },
        { x: 40.5, y: 24 },
        { x: 40.5, y: 23.6 },
        { x: 40.5, y: 23.3 },
        { x: 40.3, y: 23.2 },
        { x: 40.2, y: 22.5 },
        { x: 40.5, y: 22 },
        { x: 40.7, y: 21.6 },
        { x: 40.6, y: 21.3 },
        { x: 40.3, y: 20.7 },
        { x: 40.2, y: 20.6 },
        { x: 39.5, y: 19.8 },
        { x: 37.4, y: 22 },
        { x: 37.7, y: 22.3 },
        { x: 36.4, y: 23.6 },
        { x: 35.7, y: 23 },
        { x: 35.2, y: 23.4 },
        { x: 33.9, y: 22.1 },
        { x: 31.8, y: 24.2 },
        { x: 32.5, y: 24.9 },
        { x: 31.6, y: 25.8 },
        { x: 32.1, y: 26.3 },
        { x: 31.6, y: 26.8 },
        { x: 32.5, y: 27.7 },
        { x: 31.8, y: 28.5 },
        { x: 31.6, y: 28.4 },
        { x: 31.4, y: 28.5 },
        { x: 31.2, y: 28.2 },
        { x: 30.6, y: 28.3 },
        { x: 28.8, y: 28.2 },
        { x: 26.5, y: 30.5 },
        { x: 26.4, y: 32.7 },
        { x: 27, y: 33.3 },
        { x: 26.1, y: 34.2 },
        { x: 25.5, y: 33.7 },
        { x: 23.3, y: 36 },
        { x: 25.4, y: 38.1 },
        { x: 27.6, y: 35.8 },
        { x: 27.5, y: 35.7 },
        { x: 28.5, y: 34.7 },
        { x: 28.8, y: 34.9 },
        { x: 30.9, y: 34.9 },
        { x: 31.6, y: 34.3 },
        { x: 32.5, y: 35.3 },
        { x: 33.7, y: 34.1 },
      ],
    },
    {
      id: "nyxara-sanctuary",
      label: "Nyxara\nSanctuary",
      position: { x: 10, y: 64.8 },
      color: "#fdba74",
      outline: [
        { x: 14.6, y: 64.1 },
        { x: 14.6, y: 63.5 },
        { x: 14.2, y: 63.1 },
        { x: 14.1, y: 62.8 },
        { x: 14, y: 62.9 },
        { x: 13.9, y: 62.3 },
        { x: 13.1, y: 62.2 },
        { x: 12.4, y: 62.8 },
        { x: 11.8, y: 62.6 },
        { x: 11.7, y: 62.3 },
        { x: 10.8, y: 62.3 },
        { x: 10.7, y: 60.8 },
        { x: 11.5, y: 60.8 },
        { x: 11.5, y: 54.8 },
        { x: 10.6, y: 54.7 },
        { x: 10.7, y: 53.2 },
        { x: 9.4, y: 53.2 },
        { x: 9.2, y: 52.8 },
        { x: 8.2, y: 52.7 },
        { x: 8.2, y: 60.8 },
        { x: 9, y: 60.8 },
        { x: 9.1, y: 62.3 },
        { x: 8.8, y: 62.4 },
        { x: 8.8, y: 63.5 },
        { x: 9.2, y: 63.5 },
        { x: 9.7, y: 64.3 },
        { x: 10.6, y: 64.2 },
        { x: 11.1, y: 64.9 },
        { x: 10.5, y: 65.6 },
        { x: 9.8, y: 65.2 },
        { x: 9.3, y: 65.5 },
        { x: 9.5, y: 65.8 },
        { x: 8.9, y: 66.2 },
        { x: 8.2, y: 65.3 },
        { x: 7.6, y: 65.3 },
        { x: 7.6, y: 64.9 },
        { x: 6.7, y: 65.3 },
        { x: 6.7, y: 66.1 },
        { x: 6.2, y: 66.5 },
        { x: 5.5, y: 66.2 },
        { x: 5.4, y: 65.7 },
        { x: 5.1, y: 65.7 },
        { x: 5, y: 66.2 },
        { x: 4.3, y: 66.3 },
        { x: 4.3, y: 66.8 },
        { x: 4.7, y: 67 },
        { x: 4.8, y: 67.5 },
        { x: 4.4, y: 67.6 },
        { x: 4.4, y: 68.2 },
        { x: 4.9, y: 68.3 },
        { x: 4.9, y: 68.7 },
        { x: 5.1, y: 68.8 },
        { x: 6.3, y: 68.9 },
        { x: 6.3, y: 69.9 },
        { x: 5.4, y: 69.9 },
        { x: 5.4, y: 71.2 },
        { x: 6.3, y: 71.2 },
        { x: 6.3, y: 72.3 },
        { x: 9.4, y: 72.3 },
        { x: 9.4, y: 73 },
        { x: 11.1, y: 73 },
        { x: 11.1, y: 71.9 },
        { x: 11.7, y: 71.1 },
        { x: 12.8, y: 71.1 },
        { x: 12.7, y: 69.5 },
        { x: 13.6, y: 68.8 },
        { x: 14.2, y: 69.3 },
        { x: 14.7, y: 68.8 },
        { x: 14.6, y: 64.1 },
      ],
    },
    {
      id: "spira-insula",
      label: "Spira Insula",
      position: { x: 15.9, y: 46.1 },
      color: "#22c55e",
      outline: [
        { x: 8.2, y: 52.7 },
        { x: 9.2, y: 47.2 },
        { x: 11.9, y: 47.3 },
        { x: 12.1, y: 47 },
        { x: 13.1, y: 46.9 },
        { x: 14, y: 46.5 },
        { x: 14.4, y: 46 },
        { x: 14.5, y: 45.3 },
        { x: 14.1, y: 44.3 },
        { x: 13.3, y: 44.3 },
        { x: 13.3, y: 43.8 },
        { x: 14.2, y: 43.1 },
        { x: 15.1, y: 43.1 },
        { x: 16, y: 44 },
        { x: 16.2, y: 43.8 },
        { x: 16.7, y: 43.8 },
        { x: 17.1, y: 43.4 },
        { x: 17.7, y: 42.9 },
        { x: 18, y: 42 },
        { x: 18.5, y: 41.6 },
        { x: 18.8, y: 41.2 },
        { x: 19.2, y: 40.9 },
        { x: 19.5, y: 40.6 },
        { x: 19.5, y: 40.1 },
        { x: 20.9, y: 39.3 },
        { x: 20.8, y: 38.6 },
        { x: 23.3, y: 36.1 },
        { x: 25.4, y: 38.1 },
        { x: 24.6, y: 39.2 },
        { x: 24.6, y: 39.8 },
        { x: 24.3, y: 40.3 },
        { x: 23.9, y: 40.4 },
        { x: 21.7, y: 41.4 },
        { x: 20.8, y: 42 },
        { x: 20.6, y: 42.6 },
        { x: 19.5, y: 43 },
        { x: 19.4, y: 43.6 },
        { x: 19.8, y: 44 },
        { x: 19.4, y: 44.5 },
        { x: 19.2, y: 44.4 },
        { x: 18.9, y: 44.8 },
        { x: 18.6, y: 45 },
        { x: 18.5, y: 45.4 },
        { x: 18.1, y: 45.8 },
        { x: 18.5, y: 46.8 },
        { x: 18.2, y: 47.1 },
        { x: 18.3, y: 47.5 },
        { x: 18.6, y: 47.7 },
        { x: 18.4, y: 48 },
        { x: 18.1, y: 47.9 },
        { x: 17.7, y: 48.2 },
        { x: 17.3, y: 50.1 },
        { x: 16.9, y: 50.1 },
        { x: 16.6, y: 49.7 },
        { x: 15.6, y: 49.6 },
        { x: 15.1, y: 50.3 },
        { x: 15, y: 50.6 },
        { x: 15, y: 50.8 },
        { x: 14.5, y: 51 },
        { x: 14.5, y: 51.2 },
        { x: 14.4, y: 51.5 },
        { x: 14.1, y: 51.8 },
        { x: 13.7, y: 51.9 },
        { x: 13.3, y: 51.8 },
        { x: 13.4, y: 53.1 },
        { x: 10.7, y: 53.2 },
        { x: 9.4, y: 53.2 },
        { x: 9.2, y: 52.8 },
        { x: 8.2, y: 52.7 },
      ],
    },
    {
      id: "aranea-insula",
      label: "Aranea Insula",
      position: { x: 57.3, y: 28.4 },
      color: "#0d9488",
      outline: [
        { x: 40.2, y: 20.5 },
        { x: 44.6, y: 20.6 },
        { x: 45.6, y: 19.5 },
        { x: 46.6, y: 18.9 },
        { x: 47.5, y: 18.8 },
        { x: 48.3, y: 19 },
        { x: 48.8, y: 19.4 },
        { x: 49.5, y: 19.9 },
        { x: 50.1, y: 20.3 },
        { x: 50.9, y: 20.3 },
        { x: 52.6, y: 19.3 },
        { x: 57.1, y: 19.3 },
        { x: 58, y: 20.3 },
        { x: 58.6, y: 20.3 },
        { x: 60.1, y: 19.3 },
        { x: 63.1, y: 19.4 },
        { x: 63.8, y: 20.3 },
        { x: 64.6, y: 20.3 },
        { x: 65.8, y: 20.3 },
        { x: 68.4, y: 22.8 },
        { x: 74.5, y: 22.8 },
        { x: 73.1, y: 24.3 },
        { x: 73.1, y: 25.8 },
        { x: 74.5, y: 27 },
        { x: 75.8, y: 25.9 },
        { x: 76.3, y: 26.5 },
        { x: 65.1, y: 37.9 },
        { x: 50.8, y: 39.7 },
        { x: 50.5, y: 38.7 },
        { x: 49.8, y: 38.2 },
        { x: 49.8, y: 37.4 },
        { x: 49.2, y: 36.3 },
        { x: 48.7, y: 36.1 },
        { x: 40, y: 24.6 },
        { x: 40.5, y: 24.1 },
        { x: 40.6, y: 23.4 },
        { x: 40.4, y: 23.2 },
        { x: 40.2, y: 22.5 },
        { x: 40.9, y: 21.6 },
        { x: 40.3, y: 20.5 },
      ],
    },
    {
      id: "ruinas-insula",
      label: "Ruinas Insula",
      position: { x: 84.2, y: 46.5 },
      color: "#d946ef",
      outline: [
        { x: 75.8, y: 44.7 },
        { x: 83, y: 52.4 },
        { x: 85.8, y: 52.5 },
        { x: 89.2, y: 48.6 },
        { x: 91.9, y: 44 },
        { x: 90.2, y: 43.1 },
        { x: 89.6, y: 43.9 },
        { x: 87.9, y: 42.8 },
        { x: 88.1, y: 42 },
        { x: 87.2, y: 41.4 },
        { x: 86.8, y: 41.6 },
        { x: 86, y: 41.4 },
        { x: 85.3, y: 41.4 },
        { x: 84.6, y: 41.8 },
        { x: 83.9, y: 41.9 },
        { x: 83.7, y: 42 },
        { x: 83.5, y: 41.6 },
        { x: 82.7, y: 41.6 },
        { x: 82.3, y: 42.2 },
        { x: 82.4, y: 42.8 },
        { x: 82.5, y: 43.1 },
        { x: 82.4, y: 43.5 },
        { x: 82.2, y: 44 },
        { x: 82.1, y: 44.2 },
        { x: 81.5, y: 44.6 },
        { x: 81.3, y: 44.8 },
        { x: 81.2, y: 44.9 },
        { x: 78.4, y: 42.1 },
        { x: 75.8, y: 44.7 },
      ],
    },
    {
      id: "nyxara-inner-sanctuary",
      label: "Nyxara Inner Sanctuary",
      position: { x: 16.8, y: 76.9 },
      color: "#fde047",
      outline: [
        { x: 26.5, y: 76 },
        { x: 26.5, y: 78.3 },
        { x: 9.2, y: 78.5 },
        { x: 9.3, y: 73.1 },
        { x: 11.1, y: 73 },
        { x: 11.3, y: 76 },
        { x: 24.4, y: 76 },
        { x: 26.5, y: 76 },
      ],
    },
  ],

  // ── Easter eggs ───────────────────────────────────────────────────────────
  // A quest is stages of steps. Each step draws a dotted `path` on the map with
  // its `icon` at the end; `locations` replaces that with numbered circles when
  // an objective can spawn in one of several spots.
  eggs: [
    {
      // TODO: rename once the full quest / stage breakdown is known — this is
      // a placeholder container for the first real step.
      id: "main-quest",
      name: "Main Quest",
      color: "#ec4899",
      stages: [
        {
          id: "stage-1",
          title: "Open the Map",
          steps: [
            {
              id: "s1-activate-pack-a-punch",
              title: "Activate Pack-a-Punch",
              instruction:
                "- Unlock the House doors and go downstairs to the telephone. When a new round starts, the phone will ring.\n- Answer the phone and go through the portal to the Nexus Forge.\n- Place the World Seed into the centre of the Nexus Forge.\n- Follow and defeat the two Dread skulls.\n- Interact with the Usurped Flame each drops, and carry each flame back to the Forge to ignite its matching brazier.\n- Once both sides are lit, use the crank wheels around the Forge.\n- Pack-a-Punch is now active.",
              icon: "/images/easteregg/flame.svg",
              path: [
                { x: 57.1, y: 78.1 },
                { x: 57.7, y: 81.1 },
                { x: 55.3, y: 82.1 },
                { x: 54.3, y: 79 },
                { x: 55, y: 78.7 },
                { x: 54.7, y: 76 },
              ],
              // The portal teleports the player to Nexus Forge, so the icon
              // sits at the forge spot rather than the end of the walked path.
              iconPosition: { x: 55.4, y: 56.8 },
              // Mandatory waypoints along the route above (not alternates), so
              // solid numbered circles rather than dashed "one of several".
              solidMarkers: true,
              locations: [
                {
                  position: { x: 57.1, y: 78.1 },
                  color: "#22c55e",
                  text: "**Starting location** for this route.",
                },
                {
                  position: { x: 54.3, y: 79 },
                  text: "**Phone:** unlock the house doors and head downstairs. When a new round starts, the phone will ring — answer it.",
                },
                {
                  position: { x: 54.7, y: 76 },
                  text: "**Portal:** step through to teleport to the Nexus Forge.",
                },
              ],
            },
            {
              // Deliberately placed early: the symbol sequence takes four rounds to
              // play out, and the payoff is not needed until stage 3.
              id: "s1-house-symbol-sequence",
              title: "Start the House Symbol Sequence",
              instruction:
                "**Do this as early as you can.** It starts a four-round timer you cannot skip later, and you will not need the result until stage 3.\n\n- Look underneath the roof edge/eaves of Her House.\n- Find the small basketball tucked under it.\n- Shoot it.\n\nOver the next **four rounds**, one new symbol appears on the House each round. **Write down the order they appear in** \u2014 you have to reproduce it exactly later.\n\n**Do not shoot the symbols yet.** They are only entered during an exfil round, in stage 3.",
              // Not plotted yet — needs the basketball spot on Her House roof.
            },
          ],
        },
        {
          id: "stage-2",
          title: "Build the Warden's Blight",
          steps: [
            {
              id: "s2-fragment-of-nyxara",
              title: "Get the Fragment of Nyxara",
              instruction:
                "- Make sure you have PhD Flopper or a semtex grenade\n- Go to Dravakar's Main Chamber\n- Stand inside the chamber looking back toward the entrance, above the entrance is a small detached/narrow ledge\n- Wall Jump (or use the grapple) from there across to the top rafter\n- Look at the wall on the right hand side and destroy the breakable section with PhD Flopper or a semtex.\n- Pick up the revealed Fragment of Nyxara",
              path: [
                { x: 72.1, y: 38.8 },
                { x: 70.6, y: 38.3 },
                { x: 70.1, y: 37.6 },
                { x: 69.1, y: 38.5 },
                { x: 70.2, y: 39.4 },
                { x: 70, y: 40.1 },
                { x: 69.4, y: 40.9 },
              ],
              // Numbered steps to follow along the route above, not an icon
              // destination — no `icon`/`iconPosition` on this one.
              solidMarkers: true,
              locations: [
                { position: { x: 72.1, y: 38.8 } }, // 1 — start
                { position: { x: 70.2, y: 39.4 } }, // 2 — 5th path point
                { position: { x: 69.4, y: 40.9 } }, // 3 — final point (wall)
              ],
            },
            {
              id: "s2-purple-astral-flame",
              title: "Create the Purple Astral Flame",
              instruction:
                "- Obtain a grapple.\n- Find a floating purple orb.\n- Grapple the orb and drag it to the centre of Pack-a-Punch.\n- When it is close enough, the orb starts orbiting.\n- Turn the crank on Pack-a-Punch.\n- The Forge absorbs the orb and its fire turns purple.\n- Pick up a purple flame.\n\n**You will repeat this loop many times later:** purple orb \u2192 drag to Pack-a-Punch \u2192 crank \u2192 collect purple flame.",
              path: [
                { x: 56.7, y: 50.6 },
                { x: 55.9, y: 55.8 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 56.7, y: 50.6 } }, // 1 — grapple orb location
                { position: { x: 55.9, y: 55.8 } }, // 2 — Pack-a-Punch
              ],
            },
            {
              id: "s2-nyxara-crystal-laser",
              title: "Complete Nyxara's Crystal Laser",
              instruction:
                "- Take a purple flame from the brazier and run to the far side of Nyxara's Sanctuary\n- Throw the purple fire at the giant eye across the gap\n- A purple laser beam activates.\n- Use a grapple on each crystal the laser is currently hitting to move its position. Move each crystal to make it hit the next crystal.\n- Eventually the beam will reach a position where a crystal is missing.\n- Grapple up to the empty mounting point and insert the Fragment of Nyxara.\n- Continue rotating the crystals until the beam reaches the final receiver and opens the door to the hidden area.\n\n**Tip:** The beam appears to be timed (or perhaps ends based on the round end), so do not start until everyone is ready and try to keep a zombie alive.",
              icon: "/images/easteregg/star.svg",
              path: [
                { x: 55.4, y: 60.8 },
                { x: 44, y: 64 },
                { x: 35, y: 66.3 },
                { x: 34, y: 67.4 },
                { x: 9.4, y: 67.2 },
              ],
              // Thrown across the gap rather than walked, so the icon sits at
              // the eye instead of the last path point (the throw spot).
              iconPosition: { x: 5.9, y: 67.4 },
              solidMarkers: true,
              locations: [
                { position: { x: 55.4, y: 60.8 } }, // 1 — flame location
              ],
            },
            {
              id: "s2-feed-the-tree",
              title: "Feed the Tree and Enter the Silent Forest",
              instruction:
                "- Enter the newly opened room and fall into the Nyxara Inner Sanctuary\n- Interact with the large corrupted tree/vine\n- It begins draining your health/life essence\n- Survive while the process completes\n- When the seed becomes available, interact with it.\n- You are transported to the Silent Area / Forest\n\n**Note:** If you cannot interact with the seed, you may need to advance a round.",
              icon: "/images/easteregg/skull.svg",
              path: [
                { x: 25.3, y: 75.1 },
                { x: 25.2, y: 77.1 },
                { x: 10.2, y: 77.4 },
                { x: 10.1, y: 75.3 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 25.3, y: 75.1 } }, // 1
              ],
            },
            {
              // The Silent Forest isn't on the map, so this is just a single
              // numbered marker with the full instructions — no path.
              id: "s2-warden-blight-parts",
              title: "Collect All 3 Warden's Blight Parts",
              instruction:
                "Collect all 3 Warden's Blight parts scattered around the Silent Forest.\n\n**Item 1 — Cave:** Go toward the very rear of the forest, find the charred body near the cave entrance and interact with it, then collect the part.\n\n**Item 2 — Rock:** Find another corpse in the central area leaning against a large rock, interact and collect the part.\n\n**Item 3 — Burned Cabin:** Find the body and floorboards, melee the plank and interact with the item, then collect the part.\n\nYou can collect all three during one Forest visit if you're fast enough.\n\n**If you get kicked out before getting them all:**\n- Advance the round\n- Feed/use the tree fruit again\n- Return and collect the missing part",
              solidMarkers: true,
              locations: [{ position: { x: 30.4, y: 84.3 } }],
            },
            {
              // "Central lever" in the source notes reads as the front lever
              // near the blue writing (distinct from the actual submit lever
              // inside the central pillar at point 9) — flagged for the user
              // to confirm.
              id: "s2-four-pillars",
              title: "Solve the Four Pillars",
              instruction:
                "Go to Dravakar's Sanctuary. Four pillars each carry a celestial symbol: **galaxy**, **moon**, **star**, and **runner** (the runner is the comet/asteroid).\n\nFour levers control them \u2014 the numbers match the circles on the map:\n- Marker 4, left stairwell \u2192 rotates the two left pillars\n- Marker 3, right stairwell \u2192 rotates the two right pillars\n- Marker 2, front lever by the blue writing \u2192 rotates the front two pillars\n- Marker 5, centre pillar \u2192 **submits your answer \u2014 do not touch it until the end**\n\nInteract with the blue writing (marker 1) and Dravakar speaks one of four riddles. Note which one you get, then use the matching solution below.\n\n**These counts assume no pillar has been moved yet.** If you have already rotated some, use the end directions instead to work out what is left.\n\n**Riddle 1** \u2014 \"I remember the runner that travels to stars, while moons and galaxies stay true.\"\n- Levers: front \u00d72, right stairwell \u00d73\n- Ends as: runner \u2192 west, moon \u2192 north, galaxy \u2192 south, star \u2192 unchanged\n\n**Riddle 2** \u2014 \"I drift to the runner that travels to the moon, who borrows from galaxies when stars stay true.\"\n- Levers: left stairwell \u00d73, front \u00d72, right stairwell \u00d71\n- Ends as: runner \u2192 north, moon \u2192 south, galaxy \u2192 east, star \u2192 west\n\n**Riddle 3** \u2014 \"I drift to stars that remember moons, who borrow the runner that travels the galaxy.\"\n- Levers: left stairwell \u00d71, front \u00d72, right stairwell \u00d72\n- Ends as: runner \u2192 south, star \u2192 north, moon \u2192 east, galaxy \u2192 west\n\n**Riddle 4** \u2014 \"I remember galaxies that drift to moons, who borrow the runner that travels the stars.\"\n- Levers: left stairwell \u00d72, right stairwell \u00d72\n- An older community write-up gives the same answer as: right, right, left, left, submit.\n\nWhen the pillars are set, use the centre pillar lever (marker 5) to submit. If correct, the pillar lowers and reveals an opening in the roof. If wrong, you may have to wait for the next round to retry.",
              path: [
                { x: 78.4, y: 32.6 },
                { x: 81.3, y: 33.7 },
                { x: 79.6, y: 32 },
                { x: 80.8, y: 31.1 },
                { x: 83.3, y: 31.2 },
                { x: 85.7, y: 33.2 },
                { x: 84, y: 30.5 },
                { x: 79.7, y: 26 },
                { x: 81.1, y: 30.1 },
              ],
              solidMarkers: true,
              locations: [
                { position: { x: 78.4, y: 32.6 }, text: "Interact with the blue writing to hear Dravakar's riddle — note which one you get." }, // 1 — blue wall
                { position: { x: 81.3, y: 33.7 }, text: "Front lever — rotates the front two pillars." }, // 2 — front lever
                { position: { x: 85.7, y: 33.2 }, text: "Right stairwell lever — rotates the two right pillars." }, // 3 — right lever
                { position: { x: 79.7, y: 26 }, text: "Left stairwell lever — rotates the two left pillars." }, // 4 — left lever
                { position: { x: 81.1, y: 30.1 }, text: "Center lever — submits your answer. Do not use until the end." }, // 5 — central pillar lever
              ],
            },
            {
              id: "s2-forge-warden-blight",
              title: "Forge and Pack-a-Punch Warden's Blight",
              instruction:
                "- Look upward.\n- A previously inaccessible room has opened.\n- Grapple up.\n- Interact with the forge/anvil/build point.\n- The three Forest components create the Warden's Blight.\n- Take the Wonder Weapon.\n- Pack-a-Punch it to unlock its alt charge attack (this is needed for next step)",
              solidMarkers: true,
              locations: [{ position: { x: 82, y: 29.3 } }],
            },
          ],
        },
        {
          id: "stage-3",
          title: "Return to the House",
          steps: [
            {
              id: "s3-return-to-house",
              title: "Return to the House",
              instruction:
                "By now the four House symbols should all have appeared (see \"Start the House Symbol Sequence\" in stage 1). You need the order they originally appeared in, and the Pack-a-Punched Warden's Blight.\n\n- Wait until an exfil round starts \u2014 do not enter the symbols before then.\n- On the exfil round, shoot the four House symbols in their original order.\n- Once entered correctly, go and activate Exfil.\n- The objective changes from a normal Exfil to something like \"Go to Her House.\"\n- Complete the Exfil/HVT portion.\n- Use the resulting portal/transport to return to the House.",
              solidMarkers: true,
              locations: [{ position: { x: 55.3, y: 63.8 } }],
            },
            {
              id: "s3-eye-of-the-forge",
              title: "Get the Eye of the Forge",
              instruction:
                "Back inside Her House:\n- Go upstairs to the second floor.\n- Find the zombie window around the bedroom/bathroom area.\n- Through the window you can see the bathroom/shelf/wall area.\n- Equip the Packed Warden's Blight.\n- Fully charge its alternate attack.\n- Fire the charged blast through that zombie window at the relevant shelf/wall area.\n- The Eye of the Forge is revealed/dropped.\n- Pick it up.",
              solidMarkers: true,
              locations: [{ position: { x: 54.8, y: 80.1 } }],
            },
            {
              id: "s3-upgrade-grapple",
              title: "Upgrade the Grapple",
              instruction:
                "- Answer the phone in Her House to reveal the portal back to the main map.\n- Take the Eye back into the main map.\n- Find one of the green grapple altars/stations near Pack-a-Punch.\n- Interact with it and place the Eye of the Forge.\n- Take the grapple from **that exact same station**.\n\n**Do not pick up a grapple anywhere else afterwards.** Community testing suggests grabbing one from a different station can stop the upgraded grapple interactions working. Go straight from this station to Pack-a-Punch.",
              solidMarkers: true,
              locations: [{ position: { x: 57.3, y: 50.5 } }],
            },
          ],
        },
        {
          id: "stage-4",
          title: "Activate the True Nexus Forge",
          steps: [
            {
              id: "s4-rip-eye-panels",
              title: "Rip the Eye Panels off Pack-a-Punch",
              instruction:
                "- Go to Pack-a-Punch.\n- Look around the structure above and below it, including the Nexus Core.\n- You will see square eye-symbol panels/tiles.\n- Grapple them with the upgraded grapple.\n- They rip away, exposing web-covered mechanisms underneath.\n\n**If the panels will not come off,** you are almost certainly not holding the grapple from the station where you inserted the Eye. Go back and take that one.",
              path: [
                { x: 57.3, y: 50.5 },
                { x: 57.1, y: 52.7 },
                { x: 52.9, y: 53.6 },
                { x: 51.2, y: 56.6 },
                { x: 51.7, y: 59.5 },
                { x: 54.6, y: 61.1 },
                { x: 58.4, y: 59.8 },
                { x: 59.7, y: 57 },
                { x: 57.2, y: 53.1 },
              ],
            },
            {
              id: "s4-clear-the-webs",
              title: "Clear the Webs",
              instruction:
                "**1. Clear the normal webbing**\n\nUnderneath Pack-a-Punch, in the Nexus Core, the exposed gears are covered in webs. Fully charge the Warden's Blight alternate attack and destroy every web that responds to it.\n\n**2. Clear the final web**\n\nThe last, stubborn web will not break with the Wonder Weapon. Make another purple flame (orb \u2192 drag to Pack-a-Punch \u2192 crank \u2192 collect) and shoot that web with the flame instead. As a rule: if a web refuses the charged Wonder Weapon, use a purple flame on it.\n\n**3. Crank the Forge, then run underneath**\n\n- Go to the normal Pack-a-Punch Forge crank and turn it. **The lower control will not work until you have done this.**\n- Immediately run underneath Pack-a-Punch, toward Wunderfizz.\n- Interact with the lever in front of Wunderfizz \u2014 the one you could not use before.\n\n**Treat this as timed.** The reproduced sequence is crank \u2192 sprint underneath \u2192 activate. It has been done solo in that order, so two players operating controls at once does not appear to be required.\n\nOnce the lower control succeeds, the three large Forge/ring levers become usable on the top side of the Nexus Forge, against the pillars.",
              solidMarkers: true,
              locations: [{ position: { x: 55.3, y: 58.2 } }],
            },
            {
              id: "s4-aim-forge-laser",
              title: "Activate and Aim the Forge Laser",
              instruction:
                "Three levers now control the massive rotating rings around the Nexus Forge. The goal is to line the stone markers up so that together they form a complete **O** aimed at one Shadowsmith's temple.\n\n- Use the three levers to rotate the Forge layers.\n- Align them toward one of the four Shadowsmith temples.\n- When correctly aligned, the Forge fires a huge blue laser at that temple's Place of Power.\n\n**If a control is still hidden,** look for more eye-symbol covers on the rotating structures and rip them off with the upgraded grapple first. You should end up with three usable alignment levers.\n\n**They are not three independent switches.** Each lever moves its own section at a different rate and nudges the other two, so work the relative positions until the O closes rather than trying to set one ring at a time.\n\nYou will repeat this aiming step once per Shadowsmith temple.",
              solidMarkers: true,
              locations: [{ position: { x: 55.4, y: 60.7 } }],
            },
            {
              // Coordinates are the four temple entrances (Caltheris,
              // Dravakar, Veytharion, Nyxara) — independent, not a route.
              id: "s4-shadowsmith-corruptions",
              title: "The Four Shadowsmith Corruptions",
              instruction:
                "Each of the four temples takes three stages: **acquire** its corrupted item (different per temple), **cleanse** it, then **break** its shackle. Cleansing an altar does not finish a Shadowsmith \u2014 the shackle still has to go.\n\n**Cleansing (same for every temple)**\n\n- Take that Shadowsmith's corrupted item to its temple.\n- Place it at the temple's flame altar/cauldron.\n- Return to the Nexus Forge and aim the blue laser at that exact temple.\n- Make another purple flame and bring it back to the temple.\n- Fire the purple flame into the altar three times.\n- Dialogue and effects confirm it worked, and the altar stays lit with purple energy.\n\n**If the item is sitting there and nothing happens, check in this order:**\n- Is the right corruption item placed at this altar?\n- Is the Forge's blue laser actually aimed at this temple?\n- Are you firing a purple flame, not the Wonder Weapon?\n\n**Breaking the shackle (same for every temple)**\n\n- Once the altar is permanently lit, lead a normal zombie close to it.\n- Purple essence flows into one zombie; look closely and it radiates a specific symbol.\n- Activate the nearby Titan Trap so you can read the symbols on the giant's arm shackles.\n- Find the arm carrying the same symbol as the marked zombie.\n- Position the marked zombie so that arm is what kills it.\n- That shackle breaks. Repeat for all four Shadowsmiths.\n\n**The shackle is still not the end of a temple.** Each one then has a face tile, a shard reflector and a statue to deal with \u2014 see the next stage.",
              solidMarkers: true,
              locations: [
                { position: { x: 71.6, y: 63 }, text: "**Caltheris** temple entrance." },
                { position: { x: 64.8, y: 45.8 }, text: "**Dravakar** temple entrance." },
                { position: { x: 39.3, y: 41 }, text: "**Veytharion** temple entrance." },
                { position: { x: 31.6, y: 67.4 }, text: "**Nyxara** temple entrance." },
              ],
            },
            {
              id: "s4-dravakar-corruption",
              title: "Shadowsmith 1: Dravakar",
              instruction:
                "- Equip **Shatter Blast** on a normal weapon.\n- Go back up into the Wonder Weapon forge room above Dravakar Sanctuary.\n- Four shields sit around that room.\n- Lure zombies next to a shield and kill them there, so Shatter Blast detonates against it.\n- Use those explosions to break the shields, working through them one at a time.\n- One of them drops Dravakar's corruption item.\n\nPick it up and place it in the Dravakar altar, then follow the cleansing and shackle steps in **The Four Shadowsmith Corruptions**.",
              solidMarkers: true,
              locations: [{ position: { x: 81.9, y: 29.6 } }],
            },
            {
              id: "s4-nyxara-corruption",
              title: "Shadowsmith 2: Nyxara",
              instruction:
                "- Equip **Shadow Rift** on a weapon.\n- Make sure the blue Forge laser is aimed at the Nyxara temple.\n- Return to Nyxara's hidden tree and use the fruit again to enter the Silent Forest.\n- Head toward the cave entrance.\n- Kill zombies with Shadow Rift near the cave, aiming to trigger the actual Shadow Rift effect rather than just landing kills with it equipped.\n- Keep going until a zombie drops the **Corruption Scroll**.\n\nPick it up and place it in the Nyxara altar, then follow the cleansing and shackle steps in **The Four Shadowsmith Corruptions**.",
              solidMarkers: true,
              locations: [{ position: { x: 23.4, y: 67.4 } }],
            },
            {
              id: "s4-caltheris-corruption",
              title: "Shadowsmith 3: Caltheris",
              instruction:
                "**Solve the four pressure plates**\n\nInside Caltheris' chamber are four pressure plates/stones. For each one:\n\n- Stand on the active plate and stay on it \u2014 do not step off.\n- Four glowing lights appear around the chamber.\n- Shoot all four without leaving the plate.\n- Move to the next plate and repeat.\n\nThat is four plates \u00d7 four targets = **16 shots in total**. Completing them opens the hidden section.\n\n**Then claim the Shimmering Thread**\n\n- Interact with the revealed star/light object in the opened section.\n- Purple orbs/wisps appear.\n- Grapple the orbs and collect what they release.\n- Keep going until you receive the **Shimmering Thread**.\n\n**The drop appears to have some RNG** \u2014 there is no known way to force it, so keep releasing and looting orbs until the Thread appears.",
              solidMarkers: true,
              locations: [{ position: { x: 81.2, y: 55.7 } }],
            },
            {
              id: "s4-veytharion-puzzle",
              title: "Shadowsmith 4: Veytharion — Cube Puzzle",
              instruction:
                "**Find the four elemental cubes**\n\n- **Fire** \u2014 on top of a window in Veytharion Sanctuary, next to Mule Kick. Wall-jump to bring it down.\n- **Hand** \u2014 on the edge of Veytharion Sanctuary.\n- **Water** \u2014 on top of a column in Veytharion Main Chamber, next to a GobbleGum machine.\n- **Plant/Leaf** \u2014 near a window in Veytharion Sanctuary, by the four pillars.\n\n**Sources disagree on which perk helps spot them:** our run used Death Perception; the community guide credits Vulture Aid. Either is worth having.\n\n**Solve the puzzle**\n\nThe floor inscription is the whole rule: **fire cannot touch water or leaf/grass.** The Hand is your safe separator, so this is a river-crossing puzzle \u2014 never leave fire alone with water or leaf on either side.\n\n- Take Fire + Hand across.\n- Drop Fire on the far side, keep Hand on the transport.\n- Send Hand back.\n- Take Hand + Water across.\n- Rearrange so Hand still sits between the incompatible cubes.\n- Bring Hand back.\n- Take Leaf across, again using Hand as the separator.\n- Finally bring Fire across, keeping Hand between Fire and Water/Leaf.\n\nWhen all four are across, the wall opens and reveals a hidden area with a **blue pool/portal**, interact with it to hear an audio queue.\n\n**That same interaction is the rain trigger.** Using the portal makes the next round rain, which is what the temple purifications need — see the purification steps in **The Face Tiles and Shadow Statues**.",
              solidMarkers: true,
              locations: [{ position: { x: 37.5, y: 39.4 } }],
            },
            {
              id: "s4-veytharion-corruption",
              status: "partial",
              title: "Shadowsmith 4: Veytharion — The Sash",
              instruction:
                "**Veytharion's corruption item is the Sash.** This replaces the earlier Napalm Burst lead we published, which did not hold up.\n\nIt spawns in one of two places, on opposite sides of the map. Check both.\n\n**Spawn A — Spira Insula, near Jugger-Nog**\n\n- Head to Jugger-Nog on Spira Insula.\n- It can sit on **either side** — both spots are marked.\n- Picking it up is awkward. Expect to **grapple and interact**, or to interact while going off the edge of the map.\n\n**Spawn B — Ruinas Insula, near PhD Flopper**\n\n- Go to the Mystery Box next to PhD Flopper.\n- The Sash is on the **back side of the wall behind the box**, at the base of it.\n- **Grapple around the wall** to reach it.\n- **You will fall while grabbing it.** That is expected — **spam interact** on the way down and you will still get it.\n\nThe two Spira spots are exact. **The PhD marker is a best guess** at the position, so search the base of that back wall rather than trusting the circle.\n\n**Then it is the normal corruption process**\n\nTake the Sash to Veytharion's altar and follow the cleansing and shackle steps in **The Four Shadowsmith Corruptions** — place it, aim the Forge laser at Veytharion, three purple flames into the altar, then break the shackle with the marked zombie.",
              locations: [
                {
                  positions: [
                    { x: 11.9, y: 47 },
                    { x: 14.8, y: 51 },
                  ],
                  text: "**Spira Insula**, by Jugger-Nog — either side. Grapple-interact, or interact as you go off the edge.",
                },
                {
                  position: { x: 89.4, y: 43.7 },
                  text: "**Ruinas Insula**, by PhD Flopper — base of the back side of the wall behind the Mystery Box. Position approximate; you will fall grabbing it, so spam interact.",
                },
                {
                  // Definite spot, unlike the two dashed spawn options above.
                  position: { x: 37.3, y: 38.9 },
                  solid: true,
                  text: "**Veytharion's altar** — bring the Sash here, then three purple flames into it.",
                },
              ]
            },
          ],
        },
        {
          id: "stage-5",
          title: "The Face Tiles and Shadow Statues",
          steps: [
            {
              // All four temples run the same five-beat chain end to end.
              // Only Nyxara's aim point and statue markers are placeholders.
              id: "s5-dravakar-face-tile",
              title: "Dravakar: The Face Tile and Shard Reflector",
              instruction:
                "**Breaking the shackle does not finish a temple.** Each Shadowsmith has a further chain after it, and Dravakar's is the one that has been run start to finish.\n\n- Return to the **Dravakar main chamber**.\n- Reveal the floor tile with the **face** on it.\n- Interact with the tile and let the **quote** play out.\n- Then kill a zombie with a **frag grenade** directly on top of the tile.\n\n**The grenade kill has to land on the tile itself**, not beside it. Cook or place the grenade on the tile and walk a zombie onto it rather than throwing into a pack nearby.\n\nA **shard reflector** is revealed.\n\n- Fully charge the Warden's Blight alternate attack.\n- Shoot the reflector with it.\n\nThe reflector comes up and can now be aimed.",
              solidMarkers: true,
              locations: [{ position: { x: 70, y: 41.2 } }],
            },
            {
              id: "s5-dravakar-reflector-aim",
              title: "Dravakar: Aim the Reflector at the Corner",
              instruction:
                "The reflector has to be pointed at one specific spot in the corner of the temple.\n\n**In Dravakar that spot is the back right of the main chamber, above the zombie hole.**\n\n- Shoot the reflector to move it, the same way you redirect the Forge beam.\n- Walk it around until it points at that back-right corner, above the zombie hole.\n\n**This requires accuracy.** The target is small, and sitting a nudge off it looks identical to being on it until nothing happens. Expect to overshoot and come back rather than landing it first try.\n\nEvery temple has its own aim point — Dravakar's corner, Caltheris' top left, Nyxara's below the floor, Veytharion's back left wall. All four are written up; only Nyxara's is still an approximate area rather than a plotted spot.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 77.8, y: 38.3 },
                  text: "**The aim point** — back right of the main chamber, above the zombie hole.",
                },
                { position: { x: 70, y: 41.2 }, text: "**The reflector**, on the face tile." },
              ],
            },
            {
              id: "s5-dravakar-statue",
              title: "Dravakar: Charge the Souls and Break the Statue",
              instruction:
                "With the reflector held on the corner point:\n\n- **Kill zombies underneath the mirror.** The souls charge it.\n- Keep killing there until a **statue of Dravakar** is revealed.\n\n**If souls are not banking,** the beam has drifted off the corner point, or was never quite on it. Go back and re-aim before grinding more kills.\n\n**Break the statue**\n\n- Fully charge the Warden's Blight alternate attack.\n- **Shoot the statue in the head.**\n- Four **shadow souls** spawn.\n- Kill all four shadow souls.\n- Then destroy the statue of Dravakar.",
              solidMarkers: true,
              locations: [{ position: { x: 70, y: 41.2 } }],
            },
            {
              id: "s5-dravakar-orb-head",
              title: "Dravakar: Send an Orb into the Giant Head",
              instruction:
                "The last piece is at the **giant head over the Dravakar entrance**.\n\n- Grapple a **purple orb** and pull it beneath the giant head.\n- Hold it there, directly under the head.\n- Fully charge the Warden's Blight alternate attack and shoot the orb.\n\nThe charged shot drives the orb up into the head.\n\nOne piece of Dravakar left after this — the purification below.",
              solidMarkers: true,
              locations: [{ position: { x: 65.1, y: 45.9 } }],
            },
            {
              // The rain trigger lives in Veytharion but belongs to Dravakar's
              // chain, hence the two markers on opposite sides of the map.
              id: "s5-dravakar-purify",
              title: "Dravakar: Make it Rain, then Purify the Temple",
              instruction:
                "The last thing Dravakar needs is **rain**, and the rain is triggered over in Veytharion.\n\n**1. Trigger the rain**\n\n- Go to the **portal in Veytharion Sanctuary** — the one opened by the cube puzzle.\n- Interact with it.\n- **The next round will rain.** It does not turn over immediately, so play the current round out.\n\n**2. Purify Dravakar**\n\n- While it is raining, make a **purple flame** (orb → drag to Pack-a-Punch → crank → collect).\n- Bring it to the **giant head at Dravakar's entrance**.\n- Shoot the flame at the head's **forehead**.\n\nThe temple is now completely purified.\n\n**If the flame does nothing,** check that it is actually raining. The interaction is gated on the weather, not just on holding a flame — and the trigger only buys you the one round of it.\n\n**What the four purified temples then unlock is not documented** — see the Warden stage.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 29.8, y: 31.2 },
                  text: "**Veytharion Sanctuary portal** — interact to make the next round rain.",
                },
                {
                  position: { x: 63.6, y: 47.2 },
                  text: "**Dravakar's giant head** — purple flame to the forehead, while it rains.",
                },
              ],
            },
            {
              id: "s5-caltheris-face-tile",
              title: "Caltheris: The Face Tile and Shard Reflector",
              instruction:
                "Caltheris follows the same shape as Dravakar: a face tile, a shard reflector, a soul charge and a statue. Only the tile's activation differs.\n\n- Break Caltheris' shackle first.\n- Return to Caltheris' chamber and find the floor tile with the **face** on it.\n- **Stand on the plate** and interact with it.\n- **Stay on the plate** and **aim down sights at the Mystery Box** for **15-20 seconds**.\n\nThe tile slides away and reveals another **mirror reflector**.\n\n- Fully charge the Warden's Blight alternate attack.\n- Shoot the mirror with it.\n\nYou need the Mystery Box in view from the plate, so where the box currently sits matters. Do not step off the plate while holding ADS — the timer is on standing there aiming at it.",
              solidMarkers: true,
              locations: [{ position: { x: 79.9, y: 62.5 } }],
            },
            {
              id: "s5-caltheris-reflector-aim",
              title: "Caltheris: Aim the Reflector at the Top Left",
              instruction:
                "As with Dravakar, the reflector has to be pointed at one specific spot in the chamber.\n\n**In Caltheris that spot is the top left side of the chamber.**\n\n- Shoot the mirror to move it.\n- Walk the beam onto the top-left wall until it sits on the spot.\n\n**Accuracy matters here too.** Being slightly off looks identical to being on target right up until nothing charges. If souls will not bank in the next step, come back and re-aim before grinding more kills.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 85.8, y: 55.8 },
                  text: "**The aim point** — the top left side of the chamber.",
                },
                { position: { x: 79.9, y: 62.5 }, text: "**The reflector**, on the face tile." },
              ],
            },
            {
              id: "s5-caltheris-statue",
              title: "Caltheris: Charge the Souls and Break the Statue",
              instruction:
                "- **Kill zombies underneath the mirror** to charge souls, the same as Dravakar.\n- Keep killing until a **statue head** is revealed — it appears on the wall where the laser was landing.\n\n**Break the statue**\n\n- Fully charge the Warden's Blight alternate attack.\n- **Shoot the statue** with it.\n- Four **shadow souls** spawn.\n- Kill all four shadow souls.\n- Then destroy the statue.",
              solidMarkers: true,
              locations: [
                { position: { x: 85.8, y: 55.8 }, text: "**The statue** appears where the beam meets the wall." },
                { position: { x: 79.9, y: 62.5 }, text: "**The mirror** — kill zombies underneath it to charge souls." },
              ],
            },
            {
              id: "s5-caltheris-orb-head",
              title: "Caltheris: Send an Orb into the Giant Head",
              instruction:
                "**Identical to the Dravakar orb step**, at Caltheris' own entrance.\n\n- Grapple a **purple orb** and pull it to the **Caltheris entrance**.\n- Hold it directly beneath the **head above the entrance**.\n- Fully charge the Warden's Blight alternate attack and shoot the orb.\n\nThe charged shot raises the orb up into the Caltheris head.\n\nOne piece of Caltheris left after this — the purification below.",
              solidMarkers: true,
              locations: [{ position: { x: 73, y: 62.8 } }],
            },
            {
              id: "s5-caltheris-purify",
              title: "Caltheris: Make it Rain, then Purify the Temple",
              instruction:
                "Same rain trigger as Dravakar, aimed at Caltheris' head instead.\n\n**1. Trigger the rain**\n\n- Go to the **portal in Veytharion Sanctuary** — the one opened by the cube puzzle.\n- Interact with it.\n- **The next round will rain.** It does not turn over immediately, so play the current round out.\n\n**2. Purify Caltheris**\n\n- While it is raining, make a **purple flame** (orb → drag to Pack-a-Punch → crank → collect).\n- Bring it to the **giant head at Caltheris' entrance**.\n- Shoot the flame at the head's **forehead**.\n\nThe temple is now completely purified.\n\n**If the flame does nothing,** check that it is actually raining. The interaction is gated on the weather, not just on holding a flame.\n\n**Not confirmed, but worth planning around:** if you have more than one temple sitting at this stage, one rain round may be enough to purify several. Nobody has reported testing that, so do not build a run around it.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 29.8, y: 31.2 },
                  text: "**Veytharion Sanctuary portal** — interact to make the next round rain.",
                },
                {
                  position: { x: 73, y: 62.8 },
                  text: "**Caltheris' giant head** — purple flame to the forehead, while it rains.",
                },
              ],
            },
            {
              id: "s5-nyxara-face-tile",
              title: "Nyxara: The Face Tile and Shard Reflector",
              instruction:
                "Nyxara runs the same chain as Dravakar and Caltheris. Only the tile's activation is different — and this one is the odd one out, because it costs you a round.\n\n- Break Nyxara's shackle first.\n- Return to Nyxara and find the floor tile with the **face** on it.\n- **Interact with the plate.**\n- **Go prone on top of it.**\n- **Stay prone on the tile while the round advances.**\n\nYou have to be lying on the tile when the round rolls over, so set this up with a round nearly done rather than starting a fresh one. Keep a way to survive prone — you are not moving until it ticks.\n\nThe tile opens and reveals the **mirror reflector**.\n\n- Fully charge the Warden's Blight alternate attack.\n- Shoot the mirror to raise it.",
              solidMarkers: true,
              locations: [{ position: { x: 23.5, y: 67.1 } }],
            },
            {
              // Marker is a placeholder until the beam target is plotted
              // properly — hence "partial" rather than confirmed.
              id: "s5-nyxara-reflector-aim",
              status: "partial",
              title: "Nyxara: Aim the Reflector Below the Floor",
              instruction:
                "**In Nyxara the aim point is the bottom left, underneath the main floor level.** It is the only one of the three that points down off the main floor rather than at a wall or corner, so expect to be angling the mirror below you.\n\n- Shoot the mirror to move it.\n- Walk the beam down and left, under the main floor level, until it settles.\n\n**The exact spot is not pinned down yet.** The marker here is approximate — treat it as the right area, not the precise point, and expect to hunt within it. If souls will not bank in the next step, that is the thing to fix.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 22, y: 65 },
                  text: "**Approximate aim point** — bottom left, under the main floor level. Exact spot still to be plotted.",
                },
                { position: { x: 23.5, y: 67.1 }, text: "**The reflector**, on the face tile." },
              ],
            },
            {
              id: "s5-nyxara-statue",
              status: "partial",
              title: "Nyxara: Charge the Souls and Break the Statue",
              instruction:
                "Same as the other two temples from here.\n\n- **Kill zombies underneath the mirror** to charge souls.\n- Keep killing until the **statue** is revealed where the beam lands.\n- Fully charge the Warden's Blight alternate attack and **shoot the statue**.\n- Four **shadow souls** spawn — kill all four.\n- Then destroy the statue.\n\n**The statue marker is approximate** for the same reason as the aim point above.",
              solidMarkers: true,
              locations: [
                { position: { x: 22, y: 65 }, text: "**Approximate statue position** — where the beam lands, under the main floor." },
                { position: { x: 23.5, y: 67.1 }, text: "**The mirror** — kill zombies underneath it to charge souls." },
              ],
            },
            {
              id: "s5-nyxara-orb-head",
              title: "Nyxara: Send an Orb into the Giant Head",
              instruction:
                "Same as the Dravakar and Caltheris orb steps, at Nyxara's entrance.\n\n- Grapple a **purple orb** and drag it to the **Nyxara entrance**.\n- Hold it directly beneath the **head above the entrance**.\n- Fully charge the Warden's Blight alternate attack and shoot the orb.\n\nThe charged shot raises the orb up into the Nyxara head.\n\nOne piece of Nyxara left after this — the purification below.",
              solidMarkers: true,
              locations: [{ position: { x: 30.5, y: 67.3 } }],
            },
            {
              id: "s5-nyxara-purify",
              title: "Nyxara: Make it Rain, then Purify the Temple",
              instruction:
                "Same rain trigger again, aimed at Nyxara's head.\n\n**1. Trigger the rain**\n\n- Go to the **portal in Veytharion Sanctuary** — the one opened by the cube puzzle.\n- Interact with it.\n- **The next round will rain.** It does not turn over immediately, so play the current round out.\n\n**2. Purify Nyxara**\n\n- While it is raining, make a **purple flame** (orb → drag to Pack-a-Punch → crank → collect).\n- Bring it to the **giant head at Nyxara's entrance**.\n- Shoot the flame at the head's **forehead**.\n\n**Nyxara's head is the fiddly one.** The shape of the dragon head gets in the way of the forehead, so the flame often will not land where you need it. Keep trying and work different angles until it falls onto the forehead — if it is bouncing off, that is a positioning problem, not a sign you have the step wrong.\n\nThe temple is now completely purified.\n\n**If the flame does nothing,** check that it is actually raining. The interaction is gated on the weather, not just on holding a flame.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 29.8, y: 31.2 },
                  text: "**Veytharion Sanctuary portal** — interact to make the next round rain.",
                },
                {
                  position: { x: 30.5, y: 67.3 },
                  text: "**Nyxara's giant head** — purple flame to the forehead, while it rains.",
                },
              ],
            },
            {
              id: "s5-veytharion-face-tile",
              title: "Veytharion: The Face Tile and Shard Reflector",
              instruction:
                "The fourth and last of the face tiles, and the most tedious activation of the four.\n\n- Break Veytharion's shackle first.\n- Go back into the temple and find the **pressure plate tile with the face** on it.\n- Interact with it.\n- **Jump up and down 30 times in a row**, on the tile.\n\nIt is a straight count — get set up somewhere you can hold the spot for that long, because being interrupted off the tile means starting the jumps again.\n\nThe tile opens and reveals the **mirror reflector**.\n\n- Fully charge the Warden's Blight alternate attack.\n- Shoot the mirror to raise it.",
              solidMarkers: true,
              locations: [{ position: { x: 38, y: 39.6 } }],
            },
            {
              id: "s5-veytharion-reflector-aim",
              title: "Veytharion: Aim the Reflector at the Back Left Wall",
              instruction:
                "**In Veytharion the aim point is the back left wall of the chamber.**\n\n- Shoot the mirror to move it.\n- Walk the beam across to the back-left wall until it settles.\n\nSame as the other three: being a nudge off looks identical to being on target until the souls refuse to bank. If nothing charges in the next step, re-aim before grinding more kills.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 32, y: 36.4 },
                  text: "**The aim point** — the back left wall of the chamber.",
                },
                { position: { x: 38, y: 39.6 }, text: "**The reflector**, on the face tile." },
              ],
            },
            {
              id: "s5-veytharion-statue",
              title: "Veytharion: Charge the Souls and Break the Statue",
              instruction:
                "Same finish as the other three temples.\n\n- **Kill zombies underneath the mirror** to charge souls.\n- Keep killing until the **statue** is revealed where the beam meets the back-left wall.\n- Fully charge the Warden's Blight alternate attack and **shoot the statue**.\n- Four **shadow souls** spawn — kill all four.\n- Then destroy the statue.",
              solidMarkers: true,
              locations: [
                { position: { x: 32, y: 36.4 }, text: "**The statue** appears where the beam meets the back left wall." },
                { position: { x: 38, y: 39.6 }, text: "**The mirror** — kill zombies underneath it to charge souls." },
              ],
            },
            {
              id: "s5-veytharion-orb-head",
              title: "Veytharion: Send an Orb into the Giant Head",
              instruction:
                "Same as the other three orb steps, at Veytharion's entrance.\n\n- Grapple a **purple orb** and drag it to the **Veytharion entrance**.\n- Hold it directly beneath the **head above the entrance**.\n- Fully charge the Warden's Blight alternate attack and shoot the orb.\n\nThe charged shot raises the orb up into the Veytharion head.\n\nOne piece of Veytharion left after this — the purification below.",
              solidMarkers: true,
              locations: [{ position: { x: 41.9, y: 43.6 } }],
            },
            {
              id: "s5-veytharion-purify",
              title: "Veytharion: Make it Rain, then Purify the Temple",
              instruction:
                "The last purification, and the easiest to set up — the rain trigger is in this temple.\n\n**1. Trigger the rain**\n\n- Go to the **portal in Veytharion Sanctuary** — the one opened by the cube puzzle.\n- Interact with it.\n- **The next round will rain.** It does not turn over immediately, so play the current round out.\n\n**2. Purify Veytharion**\n\n- While it is raining, make a **purple flame** (orb → drag to Pack-a-Punch → crank → collect).\n- Bring it to the **giant head at Veytharion's entrance**.\n- Shoot the flame at the head's **forehead**.\n\nThe temple is now completely purified.\n\n**If the flame does nothing,** check that it is actually raining. The interaction is gated on the weather, not just on holding a flame.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 29.8, y: 31.2 },
                  text: "**Veytharion Sanctuary portal** — interact to make the next round rain.",
                },
                {
                  position: { x: 41.9, y: 43.6 },
                  text: "**Veytharion's giant head** — purple flame to the forehead, while it rains.",
                },
              ],
            },
          ],
        },
        {
          id: "stage-6",
          title: "The Warden",
          steps: [
            {
              id: "s6-start-final-fight",
              title: "Prepare, then Start the Final Fight",
              instruction:
                "With all four temples purified, the final fight is available. **Get set up before you trigger it** — there is no going back out for supplies once it starts.\n\n**Bring**\n\n- **Triple Pack-a-Punched weapons.** Take everything you intend to use to tier 3.\n- **GobbleGums** — whatever you have been saving.\n- **Plenty of banked essence** for ammo and buys during the fight.\n\n**Starting it**\n\n- Go down into the **Nexus Core**, beneath Pack-a-Punch.\n- Stand on the **blue portals**.\n\nThat initiates the final fight.",
              solidMarkers: true,
              locations: [
                {
                  position: { x: 55.8, y: 55.7 },
                  text: "**Nexus Core**, beneath Pack-a-Punch — stand on the blue portals.",
                },
              ],
            },
            {
              id: "s6-warden-basics",
              title: "The Warden: Fight Basics",
              instruction:
                "The whole fight runs on one loop. Get this straight before phase 1, because going for the obvious target is the wrong play.\n\n**The stun loop**\n\nThe Warden spawns **crit points**, but those are not what you shoot.\n\n- Target the **floating skulls next to him** with the Wonder Weapon.\n- Killing the skulls **stuns him**.\n- The stun exposes his real crit spot: **the tip of his tail**.\n- Burn the tail crit while the stun holds.\n\n**Grapple charges**\n\nThere are **two grapple charge locations** in the arena. **Keep using them.** The grapple is your main tool for avoiding damage for the entire fight, and running dry is what gets people killed.\n\nThe fight happens off the edge of the map, so the marker is a placement for the arena rather than a spot you walk to. The two charge points inside it are not individually mapped — find them on your first run and remember where they are.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
            {
              id: "s6-warden-phase-1",
              title: "The Warden: Phase 1",
              instruction:
                "- Run the loop: **skulls → stun → tail crit**.\n- Keep grapple charge available the whole time.\n\n**The Ava drain**\n\nPartway through, the Warden breaks off and **goes to drain Ava**.\n\n- **Shadow souls** appear.\n- **Kill the shadow souls** to bring him back into the fight.\n\nHe will not re-engage until they are dead, so do not waste time chasing him — clear the souls.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
            {
              id: "s6-warden-phase-2",
              title: "The Warden: Phase 2",
              instruction:
                "Same loop, with one substitution and one new hazard.\n\n**Skulls, or armour**\n\n- Kill the skulls to stun and expose the crit, exactly as in phase 1.\n- **If there are no skulls, look for shadow souls instead.** In this phase they act as his **armour**, and have to be destroyed before you can hurt him.\n\n**Ground tails**\n\n**Tails spawn out of the ground** to knock you off your feet and stun you.\n\n- Pop them quickly with the Wonder Weapon.\n- **Do not get drawn into fighting them.** They are obstacles, not a damage phase — clear what is in your way and get straight back on the Warden.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
            {
              id: "s6-warden-jail",
              title: "The Warden: The Jail",
              instruction:
                "Between phases 2 and 3 you are **teleported into a jail**.\n\n- **You only have to survive.**\n- **There is nothing you need to kill** — it is purely timer based.\n\nPlay it defensively, use the time to reload and recover, and wait it out.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
            {
              id: "s6-warden-phase-3",
              status: "partial",
              title: "The Warden: Phase 3",
              instruction:
                "The ground tails return, and this time they feed a **lightning attack**.\n\n**Two ways to handle it, neither fully pinned down:**\n\n- **Destroy the tails** to disrupt the attack before it goes off.\n- **Or avoid it outright.** With the timing right you can **drop off the side of the map** — or grapple off — as it fires, and come back after.\n\nThe drop-off dodge is a timing trick rather than a reliable rotation. Practise it before you build a run around it.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
            {
              id: "s6-warden-phase-4",
              status: "unconfirmed",
              title: "The Warden: Phase 4",
              instruction:
                "**There is a phase 4, and its details are not known.**\n\nThe fight does not end at phase 3 — a fourth phase is confirmed to exist — but nothing about its mechanics has been supplied or independently reproduced.\n\nThis section will be filled in once someone runs it and reports back. Do not follow leaked or cheated completion steps in the meantime.",
              solidMarkers: true,
              locations: [{ position: { x: 33.5, y: 84.7 } }],
            },
          ],
        },
      ],
    },
  ],
};
